// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/msgproto/base.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgPing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgPing) Reset()         { *m = MsgPing{} }
func (m *MsgPing) String() string { return proto.CompactTextString(m) }
func (*MsgPing) ProtoMessage()    {}
func (*MsgPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_663ae2a2023d1ef0, []int{0}
}

func (m *MsgPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPing.Unmarshal(m, b)
}
func (m *MsgPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPing.Marshal(b, m, deterministic)
}
func (m *MsgPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPing.Merge(m, src)
}
func (m *MsgPing) XXX_Size() int {
	return xxx_messageInfo_MsgPing.Size(m)
}
func (m *MsgPing) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPing.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPing proto.InternalMessageInfo

type MsgPong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgPong) Reset()         { *m = MsgPong{} }
func (m *MsgPong) String() string { return proto.CompactTextString(m) }
func (*MsgPong) ProtoMessage()    {}
func (*MsgPong) Descriptor() ([]byte, []int) {
	return fileDescriptor_663ae2a2023d1ef0, []int{1}
}

func (m *MsgPong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPong.Unmarshal(m, b)
}
func (m *MsgPong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPong.Marshal(b, m, deterministic)
}
func (m *MsgPong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPong.Merge(m, src)
}
func (m *MsgPong) XXX_Size() int {
	return xxx_messageInfo_MsgPong.Size(m)
}
func (m *MsgPong) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPong.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPong proto.InternalMessageInfo

type MsgNil struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgNil) Reset()         { *m = MsgNil{} }
func (m *MsgNil) String() string { return proto.CompactTextString(m) }
func (*MsgNil) ProtoMessage()    {}
func (*MsgNil) Descriptor() ([]byte, []int) {
	return fileDescriptor_663ae2a2023d1ef0, []int{2}
}

func (m *MsgNil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgNil.Unmarshal(m, b)
}
func (m *MsgNil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgNil.Marshal(b, m, deterministic)
}
func (m *MsgNil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNil.Merge(m, src)
}
func (m *MsgNil) XXX_Size() int {
	return xxx_messageInfo_MsgNil.Size(m)
}
func (m *MsgNil) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNil.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNil proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgPing)(nil), "msg.MsgPing")
	proto.RegisterType((*MsgPong)(nil), "msg.MsgPong")
	proto.RegisterType((*MsgNil)(nil), "msg.MsgNil")
}

func init() { proto.RegisterFile("proto/msgproto/base.proto", fileDescriptor_663ae2a2023d1ef0) }

var fileDescriptor_663ae2a2023d1ef0 = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2d, 0x4e, 0x87, 0x30, 0x92, 0x12, 0x8b, 0x53, 0xf5, 0xc0, 0x4c, 0x21, 0xe6,
	0xdc, 0xe2, 0x74, 0x25, 0x4e, 0x2e, 0x76, 0xdf, 0xe2, 0xf4, 0x80, 0xcc, 0x3c, 0x38, 0x33, 0x3f,
	0x2f, 0x5d, 0x89, 0x83, 0x8b, 0xcd, 0xb7, 0x38, 0xdd, 0x2f, 0x33, 0xc7, 0x89, 0x3d, 0x8a, 0x55,
	0xcf, 0x3a, 0xb7, 0x38, 0x3d, 0x89, 0x0d, 0xac, 0xc9, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x8a,
	0x43, 0x17, 0x7c, 0x51, 0x00, 0x00, 0x00,
}
