// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/msgproto/club.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgCreateClubReq struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ClubName             string   `protobuf:"bytes,2,opt,name=ClubName,proto3" json:"ClubName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateClubReq) Reset()         { *m = MsgCreateClubReq{} }
func (m *MsgCreateClubReq) String() string { return proto.CompactTextString(m) }
func (*MsgCreateClubReq) ProtoMessage()    {}
func (*MsgCreateClubReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a566a4ddce762802, []int{0}
}

func (m *MsgCreateClubReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateClubReq.Unmarshal(m, b)
}
func (m *MsgCreateClubReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateClubReq.Marshal(b, m, deterministic)
}
func (m *MsgCreateClubReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateClubReq.Merge(m, src)
}
func (m *MsgCreateClubReq) XXX_Size() int {
	return xxx_messageInfo_MsgCreateClubReq.Size(m)
}
func (m *MsgCreateClubReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateClubReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateClubReq proto.InternalMessageInfo

func (m *MsgCreateClubReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MsgCreateClubReq) GetClubName() string {
	if m != nil {
		return m.ClubName
	}
	return ""
}

type MsgCreateClubRes struct {
	Ret                  ErrCode   `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	Club                 *ClubInfo `protobuf:"bytes,2,opt,name=club,proto3" json:"club,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MsgCreateClubRes) Reset()         { *m = MsgCreateClubRes{} }
func (m *MsgCreateClubRes) String() string { return proto.CompactTextString(m) }
func (*MsgCreateClubRes) ProtoMessage()    {}
func (*MsgCreateClubRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a566a4ddce762802, []int{1}
}

func (m *MsgCreateClubRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateClubRes.Unmarshal(m, b)
}
func (m *MsgCreateClubRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateClubRes.Marshal(b, m, deterministic)
}
func (m *MsgCreateClubRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateClubRes.Merge(m, src)
}
func (m *MsgCreateClubRes) XXX_Size() int {
	return xxx_messageInfo_MsgCreateClubRes.Size(m)
}
func (m *MsgCreateClubRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateClubRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateClubRes proto.InternalMessageInfo

func (m *MsgCreateClubRes) GetRet() ErrCode {
	if m != nil {
		return m.Ret
	}
	return ErrCode_OK
}

func (m *MsgCreateClubRes) GetClub() *ClubInfo {
	if m != nil {
		return m.Club
	}
	return nil
}

type MsgAddClubReq struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ClubNum              string   `protobuf:"bytes,2,opt,name=ClubNum,proto3" json:"ClubNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAddClubReq) Reset()         { *m = MsgAddClubReq{} }
func (m *MsgAddClubReq) String() string { return proto.CompactTextString(m) }
func (*MsgAddClubReq) ProtoMessage()    {}
func (*MsgAddClubReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a566a4ddce762802, []int{2}
}

func (m *MsgAddClubReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAddClubReq.Unmarshal(m, b)
}
func (m *MsgAddClubReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAddClubReq.Marshal(b, m, deterministic)
}
func (m *MsgAddClubReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddClubReq.Merge(m, src)
}
func (m *MsgAddClubReq) XXX_Size() int {
	return xxx_messageInfo_MsgAddClubReq.Size(m)
}
func (m *MsgAddClubReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddClubReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddClubReq proto.InternalMessageInfo

func (m *MsgAddClubReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MsgAddClubReq) GetClubNum() string {
	if m != nil {
		return m.ClubNum
	}
	return ""
}

type MsgAddClubRes struct {
	Club                 []*ClubGeneral `protobuf:"bytes,2,rep,name=club,proto3" json:"club,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MsgAddClubRes) Reset()         { *m = MsgAddClubRes{} }
func (m *MsgAddClubRes) String() string { return proto.CompactTextString(m) }
func (*MsgAddClubRes) ProtoMessage()    {}
func (*MsgAddClubRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a566a4ddce762802, []int{3}
}

func (m *MsgAddClubRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAddClubRes.Unmarshal(m, b)
}
func (m *MsgAddClubRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAddClubRes.Marshal(b, m, deterministic)
}
func (m *MsgAddClubRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddClubRes.Merge(m, src)
}
func (m *MsgAddClubRes) XXX_Size() int {
	return xxx_messageInfo_MsgAddClubRes.Size(m)
}
func (m *MsgAddClubRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddClubRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddClubRes proto.InternalMessageInfo

func (m *MsgAddClubRes) GetClub() []*ClubGeneral {
	if m != nil {
		return m.Club
	}
	return nil
}

//简述版的俱乐部
type ClubGeneral struct {
	ClubNum              string   `protobuf:"bytes,1,opt,name=ClubNum,proto3" json:"ClubNum,omitempty"`
	ClubHeadImageUrl     string   `protobuf:"bytes,2,opt,name=ClubHeadImageUrl,proto3" json:"ClubHeadImageUrl,omitempty"`
	OnlineUserNum        int32    `protobuf:"varint,3,opt,name=OnlineUserNum,proto3" json:"OnlineUserNum,omitempty"`
	GameNum              int32    `protobuf:"varint,4,opt,name=GameNum,proto3" json:"GameNum,omitempty"`
	ClubName             string   `protobuf:"bytes,5,opt,name=ClubName,proto3" json:"ClubName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClubGeneral) Reset()         { *m = ClubGeneral{} }
func (m *ClubGeneral) String() string { return proto.CompactTextString(m) }
func (*ClubGeneral) ProtoMessage()    {}
func (*ClubGeneral) Descriptor() ([]byte, []int) {
	return fileDescriptor_a566a4ddce762802, []int{4}
}

func (m *ClubGeneral) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubGeneral.Unmarshal(m, b)
}
func (m *ClubGeneral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubGeneral.Marshal(b, m, deterministic)
}
func (m *ClubGeneral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubGeneral.Merge(m, src)
}
func (m *ClubGeneral) XXX_Size() int {
	return xxx_messageInfo_ClubGeneral.Size(m)
}
func (m *ClubGeneral) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubGeneral.DiscardUnknown(m)
}

var xxx_messageInfo_ClubGeneral proto.InternalMessageInfo

func (m *ClubGeneral) GetClubNum() string {
	if m != nil {
		return m.ClubNum
	}
	return ""
}

func (m *ClubGeneral) GetClubHeadImageUrl() string {
	if m != nil {
		return m.ClubHeadImageUrl
	}
	return ""
}

func (m *ClubGeneral) GetOnlineUserNum() int32 {
	if m != nil {
		return m.OnlineUserNum
	}
	return 0
}

func (m *ClubGeneral) GetGameNum() int32 {
	if m != nil {
		return m.GameNum
	}
	return 0
}

func (m *ClubGeneral) GetClubName() string {
	if m != nil {
		return m.ClubName
	}
	return ""
}

type ClubInfo struct {
	ClubId               uint64   `protobuf:"varint,1,opt,name=ClubId,proto3" json:"ClubId,omitempty"`
	HeadImageUrl         string   `protobuf:"bytes,2,opt,name=headImageUrl,proto3" json:"headImageUrl,omitempty"`
	ClubNum              string   `protobuf:"bytes,3,opt,name=ClubNum,proto3" json:"ClubNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClubInfo) Reset()         { *m = ClubInfo{} }
func (m *ClubInfo) String() string { return proto.CompactTextString(m) }
func (*ClubInfo) ProtoMessage()    {}
func (*ClubInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a566a4ddce762802, []int{5}
}

func (m *ClubInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubInfo.Unmarshal(m, b)
}
func (m *ClubInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubInfo.Marshal(b, m, deterministic)
}
func (m *ClubInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubInfo.Merge(m, src)
}
func (m *ClubInfo) XXX_Size() int {
	return xxx_messageInfo_ClubInfo.Size(m)
}
func (m *ClubInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClubInfo proto.InternalMessageInfo

func (m *ClubInfo) GetClubId() uint64 {
	if m != nil {
		return m.ClubId
	}
	return 0
}

func (m *ClubInfo) GetHeadImageUrl() string {
	if m != nil {
		return m.HeadImageUrl
	}
	return ""
}

func (m *ClubInfo) GetClubNum() string {
	if m != nil {
		return m.ClubNum
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgCreateClubReq)(nil), "msg.MsgCreateClubReq")
	proto.RegisterType((*MsgCreateClubRes)(nil), "msg.MsgCreateClubRes")
	proto.RegisterType((*MsgAddClubReq)(nil), "msg.MsgAddClubReq")
	proto.RegisterType((*MsgAddClubRes)(nil), "msg.MsgAddClubRes")
	proto.RegisterType((*ClubGeneral)(nil), "msg.ClubGeneral")
	proto.RegisterType((*ClubInfo)(nil), "msg.ClubInfo")
}

func init() { proto.RegisterFile("proto/msgproto/club.proto", fileDescriptor_a566a4ddce762802) }

var fileDescriptor_a566a4ddce762802 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x95, 0x49, 0x3f, 0xe0, 0xda, 0xa2, 0xca, 0x03, 0x2a, 0x15, 0x42, 0x25, 0xea, 0x10, 0x31,
	0x04, 0xa9, 0x88, 0x89, 0xa9, 0x54, 0x50, 0x3a, 0x14, 0x24, 0x4b, 0x5d, 0x98, 0x70, 0xeb, 0xc3,
	0x20, 0xc5, 0x09, 0xd8, 0xed, 0xef, 0xe2, 0x2f, 0x22, 0x3b, 0x69, 0x14, 0x37, 0x03, 0xdb, 0xbd,
	0x7b, 0x97, 0xf7, 0x9e, 0xef, 0x02, 0xe7, 0xdf, 0x3a, 0xdb, 0x66, 0x37, 0xca, 0xc8, 0xbc, 0xd8,
	0x24, 0xbb, 0x75, 0xec, 0x4a, 0x1a, 0x28, 0x23, 0x87, 0x17, 0x07, 0x3c, 0x6a, 0xbd, 0xc9, 0x04,
	0xe6, 0x23, 0xe1, 0x13, 0xf4, 0x97, 0x46, 0xce, 0x34, 0xf2, 0x2d, 0xce, 0x92, 0xdd, 0x9a, 0xe1,
	0x0f, 0x3d, 0x83, 0xd6, 0xca, 0xa0, 0x5e, 0x88, 0x01, 0x19, 0x91, 0xa8, 0xc1, 0x0a, 0x44, 0x87,
	0x70, 0x6c, 0x47, 0x5e, 0xb8, 0xc2, 0xc1, 0xd1, 0x88, 0x44, 0x27, 0xac, 0xc4, 0xe1, 0xaa, 0xa6,
	0x63, 0xe8, 0x25, 0x04, 0x0c, 0xb7, 0x4e, 0xe4, 0x74, 0xd2, 0x8d, 0x95, 0x91, 0xf1, 0xa3, 0xd6,
	0xb3, 0x4c, 0x20, 0xb3, 0x04, 0xbd, 0x82, 0x86, 0x0d, 0xeb, 0xb4, 0x3a, 0x93, 0x9e, 0x1b, 0xb0,
	0xdf, 0x2e, 0xd2, 0x8f, 0x8c, 0x39, 0x2a, 0x9c, 0x42, 0x6f, 0x69, 0xe4, 0x54, 0x88, 0xff, 0xb2,
	0x0d, 0xa0, 0xed, 0xb2, 0xec, 0x54, 0x11, 0x6d, 0x0f, 0xc3, 0x3b, 0x5f, 0xc2, 0xd0, 0x71, 0x69,
	0x1b, 0x44, 0x9d, 0x49, 0xbf, 0xb4, 0x9d, 0x63, 0x8a, 0x9a, 0x27, 0x85, 0xf3, 0x2f, 0x81, 0x4e,
	0xa5, 0x5b, 0x35, 0x20, 0x9e, 0x01, 0xbd, 0x86, 0xbe, 0x2d, 0x9f, 0x91, 0x8b, 0x85, 0xe2, 0x12,
	0x57, 0x3a, 0x29, 0x32, 0xd4, 0xfa, 0x74, 0x0c, 0xbd, 0xd7, 0x34, 0xf9, 0x4a, 0xd1, 0xc6, 0xb6,
	0x5a, 0xc1, 0x88, 0x44, 0x4d, 0xe6, 0x37, 0xad, 0xd7, 0x9c, 0x2b, 0xb4, 0x7c, 0xc3, 0xf1, 0x7b,
	0xe8, 0x9d, 0xa0, 0x79, 0x70, 0x82, 0xf7, 0x9c, 0xb3, 0xdb, 0xb3, 0x6b, 0x72, 0x75, 0xb9, 0xa6,
	0x1c, 0xd1, 0x10, 0xba, 0x9f, 0xf5, 0x9c, 0x5e, 0xaf, 0xfa, 0xd2, 0xc0, 0x7b, 0xe9, 0x43, 0xfb,
	0xad, 0x19, 0xdf, 0x2b, 0x23, 0xd7, 0x2d, 0xf7, 0xf3, 0xdc, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xe4, 0x6f, 0x3b, 0xa7, 0x7c, 0x02, 0x00, 0x00,
}
