// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/msgproto/friend.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgFriendListReq struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgFriendListReq) Reset()         { *m = MsgFriendListReq{} }
func (m *MsgFriendListReq) String() string { return proto.CompactTextString(m) }
func (*MsgFriendListReq) ProtoMessage()    {}
func (*MsgFriendListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bebe34a5833953, []int{0}
}

func (m *MsgFriendListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgFriendListReq.Unmarshal(m, b)
}
func (m *MsgFriendListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgFriendListReq.Marshal(b, m, deterministic)
}
func (m *MsgFriendListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFriendListReq.Merge(m, src)
}
func (m *MsgFriendListReq) XXX_Size() int {
	return xxx_messageInfo_MsgFriendListReq.Size(m)
}
func (m *MsgFriendListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFriendListReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFriendListReq proto.InternalMessageInfo

func (m *MsgFriendListReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type MsgFriendListRes struct {
	OnLineTotal          int32     `protobuf:"varint,1,opt,name=onLineTotal,proto3" json:"onLineTotal,omitempty"`
	Total                int32     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Friend               []*Friend `protobuf:"bytes,3,rep,name=friend,proto3" json:"friend,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MsgFriendListRes) Reset()         { *m = MsgFriendListRes{} }
func (m *MsgFriendListRes) String() string { return proto.CompactTextString(m) }
func (*MsgFriendListRes) ProtoMessage()    {}
func (*MsgFriendListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bebe34a5833953, []int{1}
}

func (m *MsgFriendListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgFriendListRes.Unmarshal(m, b)
}
func (m *MsgFriendListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgFriendListRes.Marshal(b, m, deterministic)
}
func (m *MsgFriendListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFriendListRes.Merge(m, src)
}
func (m *MsgFriendListRes) XXX_Size() int {
	return xxx_messageInfo_MsgFriendListRes.Size(m)
}
func (m *MsgFriendListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFriendListRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFriendListRes proto.InternalMessageInfo

func (m *MsgFriendListRes) GetOnLineTotal() int32 {
	if m != nil {
		return m.OnLineTotal
	}
	return 0
}

func (m *MsgFriendListRes) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *MsgFriendListRes) GetFriend() []*Friend {
	if m != nil {
		return m.Friend
	}
	return nil
}

type MsgSearchFriendReq struct {
	UserId               int32    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserNickName         string   `protobuf:"bytes,2,opt,name=UserNickName,proto3" json:"UserNickName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSearchFriendReq) Reset()         { *m = MsgSearchFriendReq{} }
func (m *MsgSearchFriendReq) String() string { return proto.CompactTextString(m) }
func (*MsgSearchFriendReq) ProtoMessage()    {}
func (*MsgSearchFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bebe34a5833953, []int{2}
}

func (m *MsgSearchFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSearchFriendReq.Unmarshal(m, b)
}
func (m *MsgSearchFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSearchFriendReq.Marshal(b, m, deterministic)
}
func (m *MsgSearchFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSearchFriendReq.Merge(m, src)
}
func (m *MsgSearchFriendReq) XXX_Size() int {
	return xxx_messageInfo_MsgSearchFriendReq.Size(m)
}
func (m *MsgSearchFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSearchFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSearchFriendReq proto.InternalMessageInfo

func (m *MsgSearchFriendReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MsgSearchFriendReq) GetUserNickName() string {
	if m != nil {
		return m.UserNickName
	}
	return ""
}

type MsgSearchFriendRes struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MsgSearchFriendRes) Reset()         { *m = MsgSearchFriendRes{} }
func (m *MsgSearchFriendRes) String() string { return proto.CompactTextString(m) }
func (*MsgSearchFriendRes) ProtoMessage()    {}
func (*MsgSearchFriendRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bebe34a5833953, []int{3}
}

func (m *MsgSearchFriendRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSearchFriendRes.Unmarshal(m, b)
}
func (m *MsgSearchFriendRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSearchFriendRes.Marshal(b, m, deterministic)
}
func (m *MsgSearchFriendRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSearchFriendRes.Merge(m, src)
}
func (m *MsgSearchFriendRes) XXX_Size() int {
	return xxx_messageInfo_MsgSearchFriendRes.Size(m)
}
func (m *MsgSearchFriendRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSearchFriendRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSearchFriendRes proto.InternalMessageInfo

func (m *MsgSearchFriendRes) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type AddFriendReq struct {
	UserId               int32    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	AddUserId            int32    `protobuf:"varint,2,opt,name=AddUserId,proto3" json:"AddUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendReq) Reset()         { *m = AddFriendReq{} }
func (m *AddFriendReq) String() string { return proto.CompactTextString(m) }
func (*AddFriendReq) ProtoMessage()    {}
func (*AddFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bebe34a5833953, []int{4}
}

func (m *AddFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendReq.Unmarshal(m, b)
}
func (m *AddFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendReq.Marshal(b, m, deterministic)
}
func (m *AddFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendReq.Merge(m, src)
}
func (m *AddFriendReq) XXX_Size() int {
	return xxx_messageInfo_AddFriendReq.Size(m)
}
func (m *AddFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendReq proto.InternalMessageInfo

func (m *AddFriendReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AddFriendReq) GetAddUserId() int32 {
	if m != nil {
		return m.AddUserId
	}
	return 0
}

type AddFriendRes struct {
	//刷新列表
	OnLineTotal          int32     `protobuf:"varint,1,opt,name=onLineTotal,proto3" json:"onLineTotal,omitempty"`
	Total                int32     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Friend               []*Friend `protobuf:"bytes,3,rep,name=friend,proto3" json:"friend,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddFriendRes) Reset()         { *m = AddFriendRes{} }
func (m *AddFriendRes) String() string { return proto.CompactTextString(m) }
func (*AddFriendRes) ProtoMessage()    {}
func (*AddFriendRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bebe34a5833953, []int{5}
}

func (m *AddFriendRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendRes.Unmarshal(m, b)
}
func (m *AddFriendRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendRes.Marshal(b, m, deterministic)
}
func (m *AddFriendRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendRes.Merge(m, src)
}
func (m *AddFriendRes) XXX_Size() int {
	return xxx_messageInfo_AddFriendRes.Size(m)
}
func (m *AddFriendRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendRes.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendRes proto.InternalMessageInfo

func (m *AddFriendRes) GetOnLineTotal() int32 {
	if m != nil {
		return m.OnLineTotal
	}
	return 0
}

func (m *AddFriendRes) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *AddFriendRes) GetFriend() []*Friend {
	if m != nil {
		return m.Friend
	}
	return nil
}

type RemoveFriendReq struct {
	UserId               int32    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	DelUserId            int32    `protobuf:"varint,2,opt,name=DelUserId,proto3" json:"DelUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFriendReq) Reset()         { *m = RemoveFriendReq{} }
func (m *RemoveFriendReq) String() string { return proto.CompactTextString(m) }
func (*RemoveFriendReq) ProtoMessage()    {}
func (*RemoveFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bebe34a5833953, []int{6}
}

func (m *RemoveFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFriendReq.Unmarshal(m, b)
}
func (m *RemoveFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFriendReq.Marshal(b, m, deterministic)
}
func (m *RemoveFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFriendReq.Merge(m, src)
}
func (m *RemoveFriendReq) XXX_Size() int {
	return xxx_messageInfo_RemoveFriendReq.Size(m)
}
func (m *RemoveFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFriendReq proto.InternalMessageInfo

func (m *RemoveFriendReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RemoveFriendReq) GetDelUserId() int32 {
	if m != nil {
		return m.DelUserId
	}
	return 0
}

//通知被移除用户  和 移除发起者  先查看被移除用户是否在线 不在线就不推送
type RemoveFriendRes struct {
	//刷新列表
	OnLineTotal          int32     `protobuf:"varint,1,opt,name=onLineTotal,proto3" json:"onLineTotal,omitempty"`
	Total                int32     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Friend               []*Friend `protobuf:"bytes,3,rep,name=friend,proto3" json:"friend,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RemoveFriendRes) Reset()         { *m = RemoveFriendRes{} }
func (m *RemoveFriendRes) String() string { return proto.CompactTextString(m) }
func (*RemoveFriendRes) ProtoMessage()    {}
func (*RemoveFriendRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bebe34a5833953, []int{7}
}

func (m *RemoveFriendRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFriendRes.Unmarshal(m, b)
}
func (m *RemoveFriendRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFriendRes.Marshal(b, m, deterministic)
}
func (m *RemoveFriendRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFriendRes.Merge(m, src)
}
func (m *RemoveFriendRes) XXX_Size() int {
	return xxx_messageInfo_RemoveFriendRes.Size(m)
}
func (m *RemoveFriendRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFriendRes.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFriendRes proto.InternalMessageInfo

func (m *RemoveFriendRes) GetOnLineTotal() int32 {
	if m != nil {
		return m.OnLineTotal
	}
	return 0
}

func (m *RemoveFriendRes) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *RemoveFriendRes) GetFriend() []*Friend {
	if m != nil {
		return m.Friend
	}
	return nil
}

type MsgNoticeFriendOnLine struct {
	OnLineUserId         int32    `protobuf:"varint,1,opt,name=onLineUserId,proto3" json:"onLineUserId,omitempty"`
	Friend               *Friend  `protobuf:"bytes,2,opt,name=friend,proto3" json:"friend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgNoticeFriendOnLine) Reset()         { *m = MsgNoticeFriendOnLine{} }
func (m *MsgNoticeFriendOnLine) String() string { return proto.CompactTextString(m) }
func (*MsgNoticeFriendOnLine) ProtoMessage()    {}
func (*MsgNoticeFriendOnLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bebe34a5833953, []int{8}
}

func (m *MsgNoticeFriendOnLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgNoticeFriendOnLine.Unmarshal(m, b)
}
func (m *MsgNoticeFriendOnLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgNoticeFriendOnLine.Marshal(b, m, deterministic)
}
func (m *MsgNoticeFriendOnLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNoticeFriendOnLine.Merge(m, src)
}
func (m *MsgNoticeFriendOnLine) XXX_Size() int {
	return xxx_messageInfo_MsgNoticeFriendOnLine.Size(m)
}
func (m *MsgNoticeFriendOnLine) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNoticeFriendOnLine.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNoticeFriendOnLine proto.InternalMessageInfo

func (m *MsgNoticeFriendOnLine) GetOnLineUserId() int32 {
	if m != nil {
		return m.OnLineUserId
	}
	return 0
}

func (m *MsgNoticeFriendOnLine) GetFriend() *Friend {
	if m != nil {
		return m.Friend
	}
	return nil
}

type MsgNoticeFriendOffLine struct {
	OffLineUserId        int32    `protobuf:"varint,1,opt,name=offLineUserId,proto3" json:"offLineUserId,omitempty"`
	Friend               *Friend  `protobuf:"bytes,2,opt,name=friend,proto3" json:"friend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgNoticeFriendOffLine) Reset()         { *m = MsgNoticeFriendOffLine{} }
func (m *MsgNoticeFriendOffLine) String() string { return proto.CompactTextString(m) }
func (*MsgNoticeFriendOffLine) ProtoMessage()    {}
func (*MsgNoticeFriendOffLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bebe34a5833953, []int{9}
}

func (m *MsgNoticeFriendOffLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgNoticeFriendOffLine.Unmarshal(m, b)
}
func (m *MsgNoticeFriendOffLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgNoticeFriendOffLine.Marshal(b, m, deterministic)
}
func (m *MsgNoticeFriendOffLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNoticeFriendOffLine.Merge(m, src)
}
func (m *MsgNoticeFriendOffLine) XXX_Size() int {
	return xxx_messageInfo_MsgNoticeFriendOffLine.Size(m)
}
func (m *MsgNoticeFriendOffLine) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNoticeFriendOffLine.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNoticeFriendOffLine proto.InternalMessageInfo

func (m *MsgNoticeFriendOffLine) GetOffLineUserId() int32 {
	if m != nil {
		return m.OffLineUserId
	}
	return 0
}

func (m *MsgNoticeFriendOffLine) GetFriend() *Friend {
	if m != nil {
		return m.Friend
	}
	return nil
}

type Friend struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	Status               int32       `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Friend) Reset()         { *m = Friend{} }
func (m *Friend) String() string { return proto.CompactTextString(m) }
func (*Friend) ProtoMessage()    {}
func (*Friend) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6bebe34a5833953, []int{10}
}

func (m *Friend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friend.Unmarshal(m, b)
}
func (m *Friend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friend.Marshal(b, m, deterministic)
}
func (m *Friend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friend.Merge(m, src)
}
func (m *Friend) XXX_Size() int {
	return xxx_messageInfo_Friend.Size(m)
}
func (m *Friend) XXX_DiscardUnknown() {
	xxx_messageInfo_Friend.DiscardUnknown(m)
}

var xxx_messageInfo_Friend proto.InternalMessageInfo

func (m *Friend) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *Friend) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgFriendListReq)(nil), "msg.MsgFriendListReq")
	proto.RegisterType((*MsgFriendListRes)(nil), "msg.MsgFriendListRes")
	proto.RegisterType((*MsgSearchFriendReq)(nil), "msg.MsgSearchFriendReq")
	proto.RegisterType((*MsgSearchFriendRes)(nil), "msg.MsgSearchFriendRes")
	proto.RegisterType((*AddFriendReq)(nil), "msg.AddFriendReq")
	proto.RegisterType((*AddFriendRes)(nil), "msg.AddFriendRes")
	proto.RegisterType((*RemoveFriendReq)(nil), "msg.RemoveFriendReq")
	proto.RegisterType((*RemoveFriendRes)(nil), "msg.RemoveFriendRes")
	proto.RegisterType((*MsgNoticeFriendOnLine)(nil), "msg.MsgNoticeFriendOnLine")
	proto.RegisterType((*MsgNoticeFriendOffLine)(nil), "msg.MsgNoticeFriendOffLine")
	proto.RegisterType((*Friend)(nil), "msg.Friend")
}

func init() { proto.RegisterFile("proto/msgproto/friend.proto", fileDescriptor_c6bebe34a5833953) }

var fileDescriptor_c6bebe34a5833953 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x0d, 0xf0, 0xb5, 0x5f, 0x98, 0x62, 0x30, 0x1b, 0x25, 0x04, 0x49, 0x24, 0xab, 0x07, 0xe2,
	0xa1, 0x24, 0x78, 0xf4, 0x84, 0x41, 0x0d, 0x09, 0x20, 0x56, 0xbd, 0x78, 0xb2, 0xb6, 0xdb, 0xda,
	0x40, 0xbb, 0xb8, 0xbb, 0x9a, 0xf8, 0xef, 0x0d, 0xbb, 0x2b, 0xb2, 0x85, 0x44, 0x3c, 0x70, 0xdb,
	0x79, 0x6f, 0x78, 0xef, 0xcd, 0x0c, 0x85, 0xa3, 0x39, 0xa3, 0x82, 0x76, 0x52, 0x1e, 0xab, 0x47,
	0xc4, 0x12, 0x92, 0x85, 0xae, 0x2c, 0x50, 0x29, 0xe5, 0x71, 0xa3, 0x99, 0xeb, 0x20, 0x8c, 0x05,
	0x34, 0x24, 0xaa, 0xa5, 0x71, 0x9c, 0x63, 0xe7, 0x33, 0xff, 0x93, 0xb0, 0x24, 0x8b, 0xa8, 0x6a,
	0xc0, 0x67, 0xb0, 0x3f, 0xe2, 0xf1, 0xb5, 0x94, 0x1d, 0x26, 0x5c, 0x78, 0xe4, 0x0d, 0xd5, 0xc0,
	0x7e, 0xe4, 0x84, 0x0d, 0xc2, 0x7a, 0xa1, 0x55, 0x68, 0xff, 0xf3, 0x74, 0x85, 0xe9, 0x5a, 0x2f,
	0x47, 0x2d, 0x70, 0x68, 0x36, 0x4c, 0x32, 0xf2, 0x40, 0x85, 0x3f, 0x93, 0x3f, 0xb0, 0xbc, 0x55,
	0x08, 0x1d, 0x80, 0x25, 0x24, 0x57, 0x94, 0x9c, 0x2a, 0xd0, 0x09, 0xd8, 0x6a, 0x96, 0x7a, 0xa9,
	0x55, 0x6a, 0x3b, 0x5d, 0xc7, 0x4d, 0x79, 0xec, 0x2a, 0x6d, 0x4f, 0x53, 0x78, 0x02, 0x68, 0xc4,
	0xe3, 0x7b, 0xe2, 0xb3, 0xe0, 0x55, 0x53, 0x6b, 0xf1, 0xac, 0xef, 0x78, 0x08, 0x43, 0x65, 0xf1,
	0x1a, 0x27, 0xc1, 0x74, 0xec, 0xa7, 0x44, 0xfa, 0x95, 0x3d, 0x03, 0xc3, 0x57, 0x1b, 0x14, 0x39,
	0xea, 0x00, 0xa8, 0xc5, 0x0c, 0xb2, 0x88, 0x4a, 0x55, 0xa7, 0x5b, 0x95, 0x81, 0x26, 0x4b, 0xd8,
	0x5b, 0x69, 0xc1, 0x7d, 0xa8, 0xf4, 0xc2, 0xf0, 0xf7, 0x48, 0x4d, 0x28, 0xf7, 0xc2, 0x50, 0x53,
	0x6a, 0xfe, 0x1f, 0x00, 0x4f, 0x0d, 0x95, 0x1d, 0xef, 0xf2, 0x06, 0xaa, 0x1e, 0x49, 0xe9, 0x07,
	0xd9, 0x2a, 0x75, 0x9f, 0xcc, 0xcc, 0xd4, 0x4b, 0x00, 0x67, 0x79, 0xa1, 0x1d, 0x07, 0x7f, 0x86,
	0xc3, 0x11, 0x8f, 0xc7, 0x54, 0x24, 0x81, 0xb6, 0xbc, 0x95, 0xc2, 0x8b, 0x7b, 0x2b, 0x0b, 0x63,
	0x08, 0x03, 0x5b, 0x71, 0x28, 0xca, 0xab, 0x6e, 0x74, 0x08, 0xa0, 0x96, 0x77, 0x88, 0x22, 0x69,
	0x71, 0x0a, 0x7b, 0x54, 0x3d, 0x0d, 0x0f, 0x13, 0xdc, 0xce, 0xe4, 0x0e, 0x6c, 0x85, 0xfc, 0xf9,
	0xdf, 0xb6, 0xb8, 0x13, 0x17, 0xbe, 0x78, 0xe7, 0x7a, 0x7b, 0xba, 0xba, 0xfc, 0xff, 0x64, 0xb9,
	0x17, 0x29, 0x8f, 0x5f, 0x6c, 0xf9, 0x2d, 0x9f, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x7c,
	0x6e, 0x3d, 0x2e, 0x04, 0x00, 0x00,
}
