// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/msgproto/login.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SelfStrUint64 struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelfStrUint64) Reset()         { *m = SelfStrUint64{} }
func (m *SelfStrUint64) String() string { return proto.CompactTextString(m) }
func (*SelfStrUint64) ProtoMessage()    {}
func (*SelfStrUint64) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a449c020fe4e80, []int{0}
}

func (m *SelfStrUint64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfStrUint64.Unmarshal(m, b)
}
func (m *SelfStrUint64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfStrUint64.Marshal(b, m, deterministic)
}
func (m *SelfStrUint64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfStrUint64.Merge(m, src)
}
func (m *SelfStrUint64) XXX_Size() int {
	return xxx_messageInfo_SelfStrUint64.Size(m)
}
func (m *SelfStrUint64) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfStrUint64.DiscardUnknown(m)
}

var xxx_messageInfo_SelfStrUint64 proto.InternalMessageInfo

func (m *SelfStrUint64) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SelfUint64 struct {
	High                 uint32   `protobuf:"varint,1,opt,name=high,proto3" json:"high,omitempty"`
	Slow                 uint32   `protobuf:"varint,2,opt,name=slow,proto3" json:"slow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelfUint64) Reset()         { *m = SelfUint64{} }
func (m *SelfUint64) String() string { return proto.CompactTextString(m) }
func (*SelfUint64) ProtoMessage()    {}
func (*SelfUint64) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a449c020fe4e80, []int{1}
}

func (m *SelfUint64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfUint64.Unmarshal(m, b)
}
func (m *SelfUint64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfUint64.Marshal(b, m, deterministic)
}
func (m *SelfUint64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfUint64.Merge(m, src)
}
func (m *SelfUint64) XXX_Size() int {
	return xxx_messageInfo_SelfUint64.Size(m)
}
func (m *SelfUint64) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfUint64.DiscardUnknown(m)
}

var xxx_messageInfo_SelfUint64 proto.InternalMessageInfo

func (m *SelfUint64) GetHigh() uint32 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *SelfUint64) GetSlow() uint32 {
	if m != nil {
		return m.Slow
	}
	return 0
}

type MsgLoginReq struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgLoginReq) Reset()         { *m = MsgLoginReq{} }
func (m *MsgLoginReq) String() string { return proto.CompactTextString(m) }
func (*MsgLoginReq) ProtoMessage()    {}
func (*MsgLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a449c020fe4e80, []int{2}
}

func (m *MsgLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgLoginReq.Unmarshal(m, b)
}
func (m *MsgLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgLoginReq.Marshal(b, m, deterministic)
}
func (m *MsgLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLoginReq.Merge(m, src)
}
func (m *MsgLoginReq) XXX_Size() int {
	return xxx_messageInfo_MsgLoginReq.Size(m)
}
func (m *MsgLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLoginReq proto.InternalMessageInfo

func (m *MsgLoginReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MsgLoginReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type MsgLoginRes struct {
	Ret                  ErrCode  `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgLoginRes) Reset()         { *m = MsgLoginRes{} }
func (m *MsgLoginRes) String() string { return proto.CompactTextString(m) }
func (*MsgLoginRes) ProtoMessage()    {}
func (*MsgLoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a449c020fe4e80, []int{3}
}

func (m *MsgLoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgLoginRes.Unmarshal(m, b)
}
func (m *MsgLoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgLoginRes.Marshal(b, m, deterministic)
}
func (m *MsgLoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLoginRes.Merge(m, src)
}
func (m *MsgLoginRes) XXX_Size() int {
	return xxx_messageInfo_MsgLoginRes.Size(m)
}
func (m *MsgLoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLoginRes proto.InternalMessageInfo

func (m *MsgLoginRes) GetRet() ErrCode {
	if m != nil {
		return m.Ret
	}
	return ErrCode_OK
}

type MsgClientSyncTimeReq struct {
	SyncInfo             int64    `protobuf:"varint,1,opt,name=syncInfo,proto3" json:"syncInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClientSyncTimeReq) Reset()         { *m = MsgClientSyncTimeReq{} }
func (m *MsgClientSyncTimeReq) String() string { return proto.CompactTextString(m) }
func (*MsgClientSyncTimeReq) ProtoMessage()    {}
func (*MsgClientSyncTimeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a449c020fe4e80, []int{4}
}

func (m *MsgClientSyncTimeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClientSyncTimeReq.Unmarshal(m, b)
}
func (m *MsgClientSyncTimeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClientSyncTimeReq.Marshal(b, m, deterministic)
}
func (m *MsgClientSyncTimeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClientSyncTimeReq.Merge(m, src)
}
func (m *MsgClientSyncTimeReq) XXX_Size() int {
	return xxx_messageInfo_MsgClientSyncTimeReq.Size(m)
}
func (m *MsgClientSyncTimeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClientSyncTimeReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClientSyncTimeReq proto.InternalMessageInfo

func (m *MsgClientSyncTimeReq) GetSyncInfo() int64 {
	if m != nil {
		return m.SyncInfo
	}
	return 0
}

type MsgClientSyncTimeRes struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Test                 int64    `protobuf:"varint,2,opt,name=test,proto3" json:"test,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClientSyncTimeRes) Reset()         { *m = MsgClientSyncTimeRes{} }
func (m *MsgClientSyncTimeRes) String() string { return proto.CompactTextString(m) }
func (*MsgClientSyncTimeRes) ProtoMessage()    {}
func (*MsgClientSyncTimeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a449c020fe4e80, []int{5}
}

func (m *MsgClientSyncTimeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClientSyncTimeRes.Unmarshal(m, b)
}
func (m *MsgClientSyncTimeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClientSyncTimeRes.Marshal(b, m, deterministic)
}
func (m *MsgClientSyncTimeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClientSyncTimeRes.Merge(m, src)
}
func (m *MsgClientSyncTimeRes) XXX_Size() int {
	return xxx_messageInfo_MsgClientSyncTimeRes.Size(m)
}
func (m *MsgClientSyncTimeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClientSyncTimeRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClientSyncTimeRes proto.InternalMessageInfo

func (m *MsgClientSyncTimeRes) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *MsgClientSyncTimeRes) GetTest() int64 {
	if m != nil {
		return m.Test
	}
	return 0
}

func init() {
	proto.RegisterType((*SelfStrUint64)(nil), "msg.SelfStrUint64")
	proto.RegisterType((*SelfUint64)(nil), "msg.SelfUint64")
	proto.RegisterType((*MsgLoginReq)(nil), "msg.MsgLoginReq")
	proto.RegisterType((*MsgLoginRes)(nil), "msg.MsgLoginRes")
	proto.RegisterType((*MsgClientSyncTimeReq)(nil), "msg.MsgClientSyncTimeReq")
	proto.RegisterType((*MsgClientSyncTimeRes)(nil), "msg.MsgClientSyncTimeRes")
}

func init() { proto.RegisterFile("proto/msgproto/login.proto", fileDescriptor_86a449c020fe4e80) }

var fileDescriptor_86a449c020fe4e80 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xe9, 0x97, 0xb6, 0x9f, 0x1d, 0xad, 0x87, 0xa5, 0x48, 0x09, 0x22, 0xb2, 0x5e, 0xbc,
	0x18, 0xa1, 0x16, 0x2f, 0xbd, 0xb5, 0x78, 0x28, 0xd8, 0xcb, 0xa6, 0xbd, 0x78, 0xab, 0xc9, 0x74,
	0x1b, 0xcc, 0xee, 0xea, 0xce, 0x8a, 0xf4, 0xdf, 0xcb, 0x4e, 0x82, 0x8a, 0x78, 0x7b, 0xde, 0xc9,
	0xfb, 0x90, 0xd9, 0x81, 0xf4, 0xd5, 0xbb, 0xe0, 0x6e, 0x0d, 0xe9, 0x06, 0x6a, 0xa7, 0x2b, 0x9b,
	0x31, 0x8b, 0xc4, 0x90, 0x4e, 0xcf, 0x7f, 0x15, 0xd0, 0xfb, 0xc2, 0x95, 0xd8, 0x54, 0xe4, 0x15,
	0x0c, 0x73, 0xac, 0x77, 0x79, 0xf0, 0x9b, 0xca, 0x86, 0xfb, 0xa9, 0x10, 0xd0, 0x2d, 0xb7, 0x61,
	0x3b, 0xee, 0x5c, 0x76, 0xae, 0x07, 0x8a, 0x59, 0x4e, 0x01, 0x62, 0xe9, 0xbb, 0xb1, 0xaf, 0xf4,
	0x9e, 0x1b, 0x43, 0xc5, 0x1c, 0x67, 0x54, 0xbb, 0x8f, 0xf1, 0xbf, 0x66, 0x16, 0x59, 0xce, 0xe0,
	0x78, 0x45, 0xfa, 0x31, 0xee, 0xa3, 0xf0, 0x4d, 0x9c, 0x41, 0x7f, 0x43, 0xe8, 0x97, 0x25, 0x8b,
	0x5d, 0xd5, 0x26, 0x31, 0x82, 0xde, 0xda, 0xbd, 0xa0, 0x65, 0x77, 0xa0, 0x9a, 0x20, 0x6f, 0x7e,
	0xca, 0x24, 0x2e, 0x20, 0x51, 0x18, 0xd8, 0x3c, 0x9d, 0x9c, 0x64, 0x86, 0x74, 0xf6, 0xe0, 0xfd,
	0xc2, 0x95, 0xa8, 0xe2, 0x07, 0x39, 0x81, 0xd1, 0x8a, 0xf4, 0xa2, 0xae, 0xd0, 0x86, 0xfc, 0x60,
	0x8b, 0x75, 0x65, 0x30, 0xfe, 0x34, 0x85, 0x23, 0x3a, 0xd8, 0x62, 0x69, 0x77, 0x8e, 0xe5, 0x44,
	0x7d, 0x65, 0x39, 0xff, 0xd3, 0xa1, 0xb8, 0xa8, 0x47, 0x7a, 0xaf, 0x43, 0x7b, 0x83, 0x36, 0xc5,
	0x37, 0x06, 0xa4, 0xc0, 0x7b, 0x26, 0x8a, 0x79, 0xfe, 0xff, 0xa9, 0x97, 0xcd, 0x0c, 0xe9, 0xe7,
	0x3e, 0x9f, 0xf3, 0xee, 0x33, 0x00, 0x00, 0xff, 0xff, 0x41, 0x7c, 0x6d, 0x1a, 0x8f, 0x01, 0x00,
	0x00,
}
