// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/msgproto/player.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//用户基本信息
type Player struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Rank                 uint64   `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Sex                  int32    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ClientId             uint64   `protobuf:"varint,6,opt,name=clientId,proto3" json:"clientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ab816d5428bcbcc, []int{0}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Player) GetRank() uint64 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *Player) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Player) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *Player) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Player) GetClientId() uint64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func init() {
	proto.RegisterType((*Player)(nil), "msg.Player")
}

func init() { proto.RegisterFile("proto/msgproto/player.proto", fileDescriptor_7ab816d5428bcbcc) }

var fileDescriptor_7ab816d5428bcbcc = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2d, 0x4e, 0x87, 0x30, 0x0a, 0x72, 0x12, 0x2b, 0x53, 0x8b, 0xf4, 0xc0, 0x1c,
	0x21, 0xe6, 0xdc, 0xe2, 0x74, 0xa5, 0x69, 0x8c, 0x5c, 0x6c, 0x01, 0x60, 0x51, 0x21, 0x31, 0x2e,
	0xb6, 0xd2, 0xe2, 0xd4, 0x22, 0xcf, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x28, 0x4f,
	0x48, 0x88, 0x8b, 0xa5, 0x28, 0x31, 0x2f, 0x5b, 0x82, 0x09, 0x2c, 0x0a, 0x66, 0x0b, 0x49, 0x71,
	0x71, 0xe4, 0x65, 0x26, 0x67, 0xfb, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2b, 0x30, 0x6a, 0x70, 0x06,
	0xc1, 0xf9, 0x42, 0x02, 0x5c, 0xcc, 0xc5, 0xa9, 0x15, 0x12, 0x2c, 0x0a, 0x8c, 0x1a, 0xac, 0x41,
	0x20, 0x26, 0xc8, 0xe4, 0xc4, 0xb2, 0xc4, 0x92, 0xc4, 0x22, 0x09, 0x56, 0xb0, 0x5a, 0x28, 0x0f,
	0x64, 0x4a, 0x72, 0x4e, 0x66, 0x6a, 0x5e, 0x89, 0x67, 0x8a, 0x04, 0x1b, 0xd8, 0x74, 0x38, 0xdf,
	0x89, 0x3d, 0x8a, 0x55, 0xcf, 0x3a, 0xb7, 0x38, 0x3d, 0x89, 0x0d, 0xec, 0x5a, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x88, 0x18, 0x1d, 0xb8, 0xcc, 0x00, 0x00, 0x00,
}
