// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/msgproto/queue.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgAddQueueReq struct {
	RoomUuid             string   `protobuf:"bytes,1,opt,name=RoomUuid,proto3" json:"RoomUuid,omitempty"`
	RoomType             int32    `protobuf:"varint,2,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	UserId               uint64   `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAddQueueReq) Reset()         { *m = MsgAddQueueReq{} }
func (m *MsgAddQueueReq) String() string { return proto.CompactTextString(m) }
func (*MsgAddQueueReq) ProtoMessage()    {}
func (*MsgAddQueueReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecc50de925adcd3a, []int{0}
}

func (m *MsgAddQueueReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAddQueueReq.Unmarshal(m, b)
}
func (m *MsgAddQueueReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAddQueueReq.Marshal(b, m, deterministic)
}
func (m *MsgAddQueueReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddQueueReq.Merge(m, src)
}
func (m *MsgAddQueueReq) XXX_Size() int {
	return xxx_messageInfo_MsgAddQueueReq.Size(m)
}
func (m *MsgAddQueueReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddQueueReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddQueueReq proto.InternalMessageInfo

func (m *MsgAddQueueReq) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *MsgAddQueueReq) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *MsgAddQueueReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type MsgAddQueueRes struct {
	Ret                  ErrCode  `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAddQueueRes) Reset()         { *m = MsgAddQueueRes{} }
func (m *MsgAddQueueRes) String() string { return proto.CompactTextString(m) }
func (*MsgAddQueueRes) ProtoMessage()    {}
func (*MsgAddQueueRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecc50de925adcd3a, []int{1}
}

func (m *MsgAddQueueRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAddQueueRes.Unmarshal(m, b)
}
func (m *MsgAddQueueRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAddQueueRes.Marshal(b, m, deterministic)
}
func (m *MsgAddQueueRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddQueueRes.Merge(m, src)
}
func (m *MsgAddQueueRes) XXX_Size() int {
	return xxx_messageInfo_MsgAddQueueRes.Size(m)
}
func (m *MsgAddQueueRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddQueueRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddQueueRes proto.InternalMessageInfo

func (m *MsgAddQueueRes) GetRet() ErrCode {
	if m != nil {
		return m.Ret
	}
	return ErrCode_OK
}

type MsgQuitQueueReq struct {
	RoomUuid             string   `protobuf:"bytes,1,opt,name=RoomUuid,proto3" json:"RoomUuid,omitempty"`
	RoomType             int32    `protobuf:"varint,2,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	UserId               uint64   `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgQuitQueueReq) Reset()         { *m = MsgQuitQueueReq{} }
func (m *MsgQuitQueueReq) String() string { return proto.CompactTextString(m) }
func (*MsgQuitQueueReq) ProtoMessage()    {}
func (*MsgQuitQueueReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecc50de925adcd3a, []int{2}
}

func (m *MsgQuitQueueReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgQuitQueueReq.Unmarshal(m, b)
}
func (m *MsgQuitQueueReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgQuitQueueReq.Marshal(b, m, deterministic)
}
func (m *MsgQuitQueueReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQuitQueueReq.Merge(m, src)
}
func (m *MsgQuitQueueReq) XXX_Size() int {
	return xxx_messageInfo_MsgQuitQueueReq.Size(m)
}
func (m *MsgQuitQueueReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQuitQueueReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQuitQueueReq proto.InternalMessageInfo

func (m *MsgQuitQueueReq) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *MsgQuitQueueReq) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *MsgQuitQueueReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type MsgQuitQueueRes struct {
	Ret                  ErrCode  `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgQuitQueueRes) Reset()         { *m = MsgQuitQueueRes{} }
func (m *MsgQuitQueueRes) String() string { return proto.CompactTextString(m) }
func (*MsgQuitQueueRes) ProtoMessage()    {}
func (*MsgQuitQueueRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecc50de925adcd3a, []int{3}
}

func (m *MsgQuitQueueRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgQuitQueueRes.Unmarshal(m, b)
}
func (m *MsgQuitQueueRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgQuitQueueRes.Marshal(b, m, deterministic)
}
func (m *MsgQuitQueueRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQuitQueueRes.Merge(m, src)
}
func (m *MsgQuitQueueRes) XXX_Size() int {
	return xxx_messageInfo_MsgQuitQueueRes.Size(m)
}
func (m *MsgQuitQueueRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQuitQueueRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQuitQueueRes proto.InternalMessageInfo

func (m *MsgQuitQueueRes) GetRet() ErrCode {
	if m != nil {
		return m.Ret
	}
	return ErrCode_OK
}

type MsgMatchReq struct {
	ClientId             uint64   `protobuf:"varint,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgMatchReq) Reset()         { *m = MsgMatchReq{} }
func (m *MsgMatchReq) String() string { return proto.CompactTextString(m) }
func (*MsgMatchReq) ProtoMessage()    {}
func (*MsgMatchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecc50de925adcd3a, []int{4}
}

func (m *MsgMatchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgMatchReq.Unmarshal(m, b)
}
func (m *MsgMatchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgMatchReq.Marshal(b, m, deterministic)
}
func (m *MsgMatchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMatchReq.Merge(m, src)
}
func (m *MsgMatchReq) XXX_Size() int {
	return xxx_messageInfo_MsgMatchReq.Size(m)
}
func (m *MsgMatchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMatchReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMatchReq proto.InternalMessageInfo

func (m *MsgMatchReq) GetClientId() uint64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

type MsgMatchRes struct {
	Ret                  ErrCode  `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	TableId              string   `protobuf:"bytes,2,opt,name=TableId,proto3" json:"TableId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgMatchRes) Reset()         { *m = MsgMatchRes{} }
func (m *MsgMatchRes) String() string { return proto.CompactTextString(m) }
func (*MsgMatchRes) ProtoMessage()    {}
func (*MsgMatchRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecc50de925adcd3a, []int{5}
}

func (m *MsgMatchRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgMatchRes.Unmarshal(m, b)
}
func (m *MsgMatchRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgMatchRes.Marshal(b, m, deterministic)
}
func (m *MsgMatchRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMatchRes.Merge(m, src)
}
func (m *MsgMatchRes) XXX_Size() int {
	return xxx_messageInfo_MsgMatchRes.Size(m)
}
func (m *MsgMatchRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMatchRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMatchRes proto.InternalMessageInfo

func (m *MsgMatchRes) GetRet() ErrCode {
	if m != nil {
		return m.Ret
	}
	return ErrCode_OK
}

func (m *MsgMatchRes) GetTableId() string {
	if m != nil {
		return m.TableId
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgAddQueueReq)(nil), "msg.MsgAddQueueReq")
	proto.RegisterType((*MsgAddQueueRes)(nil), "msg.MsgAddQueueRes")
	proto.RegisterType((*MsgQuitQueueReq)(nil), "msg.MsgQuitQueueReq")
	proto.RegisterType((*MsgQuitQueueRes)(nil), "msg.MsgQuitQueueRes")
	proto.RegisterType((*MsgMatchReq)(nil), "msg.MsgMatchReq")
	proto.RegisterType((*MsgMatchRes)(nil), "msg.MsgMatchRes")
}

func init() { proto.RegisterFile("proto/msgproto/queue.proto", fileDescriptor_ecc50de925adcd3a) }

var fileDescriptor_ecc50de925adcd3a = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2d, 0x4e, 0x87, 0x30, 0x0a, 0x4b, 0x53, 0x4b, 0x53, 0xf5, 0xc0, 0x6c, 0x21,
	0xe6, 0xdc, 0xe2, 0x74, 0x29, 0x19, 0x34, 0x05, 0xa9, 0x45, 0x45, 0xc9, 0xf9, 0x29, 0x50, 0x25,
	0x4a, 0x09, 0x5c, 0x7c, 0xbe, 0xc5, 0xe9, 0x8e, 0x29, 0x29, 0x81, 0x20, 0x7d, 0x41, 0xa9, 0x85,
	0x42, 0x52, 0x5c, 0x1c, 0x41, 0xf9, 0xf9, 0xb9, 0xa1, 0xa5, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x70, 0x3e, 0x4c, 0x2e, 0xa4, 0xb2, 0x20, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83,
	0x35, 0x08, 0xce, 0x17, 0x12, 0xe3, 0x62, 0x0b, 0x2d, 0x4e, 0x2d, 0xf2, 0x4c, 0x91, 0x60, 0x56,
	0x60, 0xd4, 0x60, 0x09, 0x82, 0xf2, 0x94, 0x0c, 0xd0, 0x6c, 0x28, 0x16, 0x92, 0xe3, 0x62, 0x0e,
	0x4a, 0x2d, 0x01, 0x1b, 0xce, 0x67, 0xc4, 0xa3, 0x97, 0x5b, 0x9c, 0xae, 0xe7, 0x5a, 0x54, 0xe4,
	0x9c, 0x9f, 0x92, 0x1a, 0x04, 0x92, 0x50, 0x4a, 0xe4, 0xe2, 0xf7, 0x2d, 0x4e, 0x0f, 0x2c, 0xcd,
	0x2c, 0xa1, 0x99, 0xa3, 0x0c, 0xd1, 0xad, 0x20, 0xec, 0x2a, 0x4d, 0x2e, 0x6e, 0xdf, 0xe2, 0x74,
	0xdf, 0xc4, 0x92, 0xe4, 0x0c, 0xa8, 0x8b, 0x9c, 0x73, 0x32, 0x53, 0xf3, 0x4a, 0x3c, 0x21, 0x2e,
	0x62, 0x09, 0x82, 0xf3, 0x95, 0xdc, 0x91, 0x95, 0x12, 0x34, 0x59, 0x48, 0x82, 0x8b, 0x3d, 0x24,
	0x31, 0x29, 0x27, 0xd5, 0x33, 0x05, 0xec, 0x7e, 0xce, 0x20, 0x18, 0xd7, 0x89, 0x3d, 0x8a, 0x55,
	0xcf, 0x3a, 0xb7, 0x38, 0x3d, 0x89, 0x0d, 0x1c, 0x5b, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xfe, 0x38, 0x47, 0x08, 0xee, 0x01, 0x00, 0x00,
}
