// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/msgproto/room.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgCreateRoomReq struct {
	RoomType             int32       `protobuf:"varint,1,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	PlayerInfo           *PlayerInfo `protobuf:"bytes,2,opt,name=PlayerInfo,proto3" json:"PlayerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MsgCreateRoomReq) Reset()         { *m = MsgCreateRoomReq{} }
func (m *MsgCreateRoomReq) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRoomReq) ProtoMessage()    {}
func (*MsgCreateRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{0}
}

func (m *MsgCreateRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateRoomReq.Unmarshal(m, b)
}
func (m *MsgCreateRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateRoomReq.Marshal(b, m, deterministic)
}
func (m *MsgCreateRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRoomReq.Merge(m, src)
}
func (m *MsgCreateRoomReq) XXX_Size() int {
	return xxx_messageInfo_MsgCreateRoomReq.Size(m)
}
func (m *MsgCreateRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRoomReq proto.InternalMessageInfo

func (m *MsgCreateRoomReq) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *MsgCreateRoomReq) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type MsgCreateRoomRes struct {
	Ret                  ErrCode  `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	RoomUuid             string   `protobuf:"bytes,2,opt,name=RoomUuid,proto3" json:"RoomUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateRoomRes) Reset()         { *m = MsgCreateRoomRes{} }
func (m *MsgCreateRoomRes) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRoomRes) ProtoMessage()    {}
func (*MsgCreateRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{1}
}

func (m *MsgCreateRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateRoomRes.Unmarshal(m, b)
}
func (m *MsgCreateRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateRoomRes.Marshal(b, m, deterministic)
}
func (m *MsgCreateRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRoomRes.Merge(m, src)
}
func (m *MsgCreateRoomRes) XXX_Size() int {
	return xxx_messageInfo_MsgCreateRoomRes.Size(m)
}
func (m *MsgCreateRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRoomRes proto.InternalMessageInfo

func (m *MsgCreateRoomRes) GetRet() ErrCode {
	if m != nil {
		return m.Ret
	}
	return ErrCode_OK
}

func (m *MsgCreateRoomRes) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

type MsgAddRoomReq struct {
	RoomUuid             string      `protobuf:"bytes,1,opt,name=RoomUuid,proto3" json:"RoomUuid,omitempty"`
	PlayerInfo           *PlayerInfo `protobuf:"bytes,2,opt,name=PlayerInfo,proto3" json:"PlayerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MsgAddRoomReq) Reset()         { *m = MsgAddRoomReq{} }
func (m *MsgAddRoomReq) String() string { return proto.CompactTextString(m) }
func (*MsgAddRoomReq) ProtoMessage()    {}
func (*MsgAddRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{2}
}

func (m *MsgAddRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAddRoomReq.Unmarshal(m, b)
}
func (m *MsgAddRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAddRoomReq.Marshal(b, m, deterministic)
}
func (m *MsgAddRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddRoomReq.Merge(m, src)
}
func (m *MsgAddRoomReq) XXX_Size() int {
	return xxx_messageInfo_MsgAddRoomReq.Size(m)
}
func (m *MsgAddRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddRoomReq proto.InternalMessageInfo

func (m *MsgAddRoomReq) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *MsgAddRoomReq) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type MsgAddRoomRes struct {
	Ret                  ErrCode  `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAddRoomRes) Reset()         { *m = MsgAddRoomRes{} }
func (m *MsgAddRoomRes) String() string { return proto.CompactTextString(m) }
func (*MsgAddRoomRes) ProtoMessage()    {}
func (*MsgAddRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{3}
}

func (m *MsgAddRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAddRoomRes.Unmarshal(m, b)
}
func (m *MsgAddRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAddRoomRes.Marshal(b, m, deterministic)
}
func (m *MsgAddRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddRoomRes.Merge(m, src)
}
func (m *MsgAddRoomRes) XXX_Size() int {
	return xxx_messageInfo_MsgAddRoomRes.Size(m)
}
func (m *MsgAddRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddRoomRes proto.InternalMessageInfo

func (m *MsgAddRoomRes) GetRet() ErrCode {
	if m != nil {
		return m.Ret
	}
	return ErrCode_OK
}

//同步房间已有用户
type MsgClientOnRoomRes struct {
	RoomPlayer           []*PlayerInfo `protobuf:"bytes,1,rep,name=RoomPlayer,proto3" json:"RoomPlayer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MsgClientOnRoomRes) Reset()         { *m = MsgClientOnRoomRes{} }
func (m *MsgClientOnRoomRes) String() string { return proto.CompactTextString(m) }
func (*MsgClientOnRoomRes) ProtoMessage()    {}
func (*MsgClientOnRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{4}
}

func (m *MsgClientOnRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClientOnRoomRes.Unmarshal(m, b)
}
func (m *MsgClientOnRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClientOnRoomRes.Marshal(b, m, deterministic)
}
func (m *MsgClientOnRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClientOnRoomRes.Merge(m, src)
}
func (m *MsgClientOnRoomRes) XXX_Size() int {
	return xxx_messageInfo_MsgClientOnRoomRes.Size(m)
}
func (m *MsgClientOnRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClientOnRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClientOnRoomRes proto.InternalMessageInfo

func (m *MsgClientOnRoomRes) GetRoomPlayer() []*PlayerInfo {
	if m != nil {
		return m.RoomPlayer
	}
	return nil
}

type MsgQuitRoomReq struct {
	RoomUuid             string   `protobuf:"bytes,1,opt,name=RoomUuid,proto3" json:"RoomUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgQuitRoomReq) Reset()         { *m = MsgQuitRoomReq{} }
func (m *MsgQuitRoomReq) String() string { return proto.CompactTextString(m) }
func (*MsgQuitRoomReq) ProtoMessage()    {}
func (*MsgQuitRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{5}
}

func (m *MsgQuitRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgQuitRoomReq.Unmarshal(m, b)
}
func (m *MsgQuitRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgQuitRoomReq.Marshal(b, m, deterministic)
}
func (m *MsgQuitRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQuitRoomReq.Merge(m, src)
}
func (m *MsgQuitRoomReq) XXX_Size() int {
	return xxx_messageInfo_MsgQuitRoomReq.Size(m)
}
func (m *MsgQuitRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQuitRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQuitRoomReq proto.InternalMessageInfo

func (m *MsgQuitRoomReq) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

type MsgQuitRoomRes struct {
	Ret                  ErrCode  `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgQuitRoomRes) Reset()         { *m = MsgQuitRoomRes{} }
func (m *MsgQuitRoomRes) String() string { return proto.CompactTextString(m) }
func (*MsgQuitRoomRes) ProtoMessage()    {}
func (*MsgQuitRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{6}
}

func (m *MsgQuitRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgQuitRoomRes.Unmarshal(m, b)
}
func (m *MsgQuitRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgQuitRoomRes.Marshal(b, m, deterministic)
}
func (m *MsgQuitRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQuitRoomRes.Merge(m, src)
}
func (m *MsgQuitRoomRes) XXX_Size() int {
	return xxx_messageInfo_MsgQuitRoomRes.Size(m)
}
func (m *MsgQuitRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQuitRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQuitRoomRes proto.InternalMessageInfo

func (m *MsgQuitRoomRes) GetRet() ErrCode {
	if m != nil {
		return m.Ret
	}
	return ErrCode_OK
}

// uuid string //房间uuid
//roomName string //房间名字
//ownerCid uint64
//roomType int32 //房间类型
//avgRank uint64 //房间平均分数
//roomClientNum int32 //房间人数
//owner *common.PlayerInfo
//otherUsers []*common.PlayerInfo
type Room struct {
	Uuid                 string        `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	RoomName             string        `protobuf:"bytes,2,opt,name=RoomName,proto3" json:"RoomName,omitempty"`
	RoomType             int32         `protobuf:"varint,3,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	AvgRank              uint64        `protobuf:"varint,4,opt,name=AvgRank,proto3" json:"AvgRank,omitempty"`
	RoomClientNum        int32         `protobuf:"varint,5,opt,name=RoomClientNum,proto3" json:"RoomClientNum,omitempty"`
	Owner                *PlayerInfo   `protobuf:"bytes,6,opt,name=Owner,proto3" json:"Owner,omitempty"`
	OtherClients         []*PlayerInfo `protobuf:"bytes,7,rep,name=OtherClients,proto3" json:"OtherClients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{7}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Room) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *Room) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *Room) GetAvgRank() uint64 {
	if m != nil {
		return m.AvgRank
	}
	return 0
}

func (m *Room) GetRoomClientNum() int32 {
	if m != nil {
		return m.RoomClientNum
	}
	return 0
}

func (m *Room) GetOwner() *PlayerInfo {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Room) GetOtherClients() []*PlayerInfo {
	if m != nil {
		return m.OtherClients
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgCreateRoomReq)(nil), "msg.MsgCreateRoomReq")
	proto.RegisterType((*MsgCreateRoomRes)(nil), "msg.MsgCreateRoomRes")
	proto.RegisterType((*MsgAddRoomReq)(nil), "msg.MsgAddRoomReq")
	proto.RegisterType((*MsgAddRoomRes)(nil), "msg.MsgAddRoomRes")
	proto.RegisterType((*MsgClientOnRoomRes)(nil), "msg.MsgClientOnRoomRes")
	proto.RegisterType((*MsgQuitRoomReq)(nil), "msg.MsgQuitRoomReq")
	proto.RegisterType((*MsgQuitRoomRes)(nil), "msg.MsgQuitRoomRes")
	proto.RegisterType((*Room)(nil), "msg.Room")
}

func init() { proto.RegisterFile("proto/msgproto/room.proto", fileDescriptor_56821081eb5e5870) }

var fileDescriptor_56821081eb5e5870 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4f, 0xea, 0x40,
	0x10, 0xc7, 0xd3, 0xd7, 0x16, 0xde, 0x9b, 0x07, 0x68, 0xf6, 0xb4, 0x12, 0xa3, 0x4d, 0xa3, 0x09,
	0x07, 0xd3, 0x1a, 0x38, 0x7a, 0x42, 0xc2, 0xc1, 0x03, 0xa0, 0x1b, 0xbd, 0x18, 0x13, 0x53, 0xed,
	0xb2, 0x36, 0xb2, 0x5d, 0xdc, 0x2d, 0x1a, 0xbe, 0xb4, 0x9f, 0xc1, 0x74, 0x37, 0x05, 0x5a, 0x49,
	0xd0, 0xdb, 0x4c, 0xe7, 0x37, 0xff, 0xf9, 0xef, 0x74, 0xe0, 0x60, 0x2e, 0x45, 0x26, 0x42, 0xae,
	0x98, 0x09, 0xa4, 0x10, 0x3c, 0xd0, 0x21, 0xb2, 0xb9, 0x62, 0xed, 0xc3, 0x4a, 0x9d, 0x4a, 0xf9,
	0x2c, 0x62, 0x6a, 0x90, 0xf6, 0x71, 0xa5, 0x3a, 0x9f, 0x45, 0x4b, 0x2a, 0x93, 0x74, 0x2a, 0x0c,
	0xe0, 0x3f, 0xc2, 0xfe, 0x48, 0xb1, 0x81, 0xa4, 0x51, 0x46, 0x89, 0x10, 0x9c, 0xd0, 0x37, 0xd4,
	0x86, 0xbf, 0x79, 0x78, 0xbb, 0x9c, 0x53, 0x6c, 0x79, 0x56, 0xc7, 0x25, 0xab, 0x1c, 0x85, 0x00,
	0xd7, 0x5a, 0xe3, 0x2a, 0x9d, 0x0a, 0xfc, 0xc7, 0xb3, 0x3a, 0xff, 0xbb, 0x7b, 0x01, 0x57, 0x2c,
	0x58, 0x7f, 0x26, 0x1b, 0x88, 0x3f, 0xfe, 0x36, 0x40, 0xa1, 0x23, 0xb0, 0x09, 0xcd, 0xb4, 0x76,
	0xab, 0xdb, 0xd0, 0xdd, 0x43, 0x29, 0x07, 0x22, 0xa6, 0x24, 0x2f, 0x14, 0x06, 0xee, 0x16, 0x49,
	0xac, 0x47, 0xfc, 0x23, 0xab, 0xdc, 0x7f, 0x80, 0xe6, 0x48, 0xb1, 0x7e, 0x1c, 0x57, 0xdc, 0x6a,
	0xd8, 0x2a, 0xc3, 0xbf, 0x77, 0x1b, 0x96, 0xd5, 0x77, 0x5a, 0xf5, 0x87, 0x80, 0xf2, 0xe7, 0xcd,
	0x12, 0x9a, 0x66, 0x93, 0xb4, 0xe8, 0x0a, 0x01, 0xf2, 0xd0, 0x08, 0x63, 0xcb, 0xb3, 0xb7, 0xce,
	0x5d, 0x23, 0xfe, 0x19, 0xb4, 0x46, 0x8a, 0xdd, 0x2c, 0x92, 0xec, 0x07, 0xcf, 0xf2, 0xcf, 0x2b,
	0xf4, 0x6e, 0x9b, 0x9f, 0x16, 0x38, 0x39, 0x8b, 0x10, 0x38, 0x1b, 0x92, 0x3a, 0x2e, 0x46, 0x8d,
	0x23, 0x4e, 0x37, 0xd7, 0x9d, 0xe7, 0xa5, 0x5b, 0xb0, 0x2b, 0xb7, 0x80, 0xa1, 0xde, 0x7f, 0x67,
	0x24, 0x4a, 0x5f, 0xb1, 0xe3, 0x59, 0x1d, 0x87, 0x14, 0x29, 0x3a, 0x81, 0x66, 0x4e, 0x99, 0xb5,
	0x8c, 0x17, 0x1c, 0xbb, 0xba, 0xb5, 0xfc, 0x11, 0x9d, 0x82, 0x3b, 0xf9, 0x48, 0xa9, 0xc4, 0xb5,
	0xed, 0x3f, 0xc6, 0x54, 0x51, 0x0f, 0x1a, 0x93, 0xec, 0x85, 0x4a, 0xd3, 0xa8, 0x70, 0x7d, 0xfb,
	0x3a, 0x4b, 0xd0, 0x65, 0xfd, 0xde, 0x0d, 0x2e, 0xb8, 0x62, 0x4f, 0x35, 0x7d, 0xe7, 0xbd, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xe3, 0xf1, 0x36, 0xc1, 0x48, 0x03, 0x00, 0x00,
}
