// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/msgproto/room.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgCreateRoomReq struct {
	RoomType             int32       `protobuf:"varint,1,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	PlayerInfo           *PlayerInfo `protobuf:"bytes,2,opt,name=PlayerInfo,proto3" json:"PlayerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MsgCreateRoomReq) Reset()         { *m = MsgCreateRoomReq{} }
func (m *MsgCreateRoomReq) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRoomReq) ProtoMessage()    {}
func (*MsgCreateRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{0}
}

func (m *MsgCreateRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateRoomReq.Unmarshal(m, b)
}
func (m *MsgCreateRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateRoomReq.Marshal(b, m, deterministic)
}
func (m *MsgCreateRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRoomReq.Merge(m, src)
}
func (m *MsgCreateRoomReq) XXX_Size() int {
	return xxx_messageInfo_MsgCreateRoomReq.Size(m)
}
func (m *MsgCreateRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRoomReq proto.InternalMessageInfo

func (m *MsgCreateRoomReq) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *MsgCreateRoomReq) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type MsgCreateRoomRes struct {
	Ret                  ErrCode  `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	Room                 *Room    `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateRoomRes) Reset()         { *m = MsgCreateRoomRes{} }
func (m *MsgCreateRoomRes) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRoomRes) ProtoMessage()    {}
func (*MsgCreateRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{1}
}

func (m *MsgCreateRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateRoomRes.Unmarshal(m, b)
}
func (m *MsgCreateRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateRoomRes.Marshal(b, m, deterministic)
}
func (m *MsgCreateRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRoomRes.Merge(m, src)
}
func (m *MsgCreateRoomRes) XXX_Size() int {
	return xxx_messageInfo_MsgCreateRoomRes.Size(m)
}
func (m *MsgCreateRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRoomRes proto.InternalMessageInfo

func (m *MsgCreateRoomRes) GetRet() ErrCode {
	if m != nil {
		return m.Ret
	}
	return ErrCode_OK
}

func (m *MsgCreateRoomRes) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

type MsgRoomListReq struct {
	RoomType             int32    `protobuf:"varint,1,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRoomListReq) Reset()         { *m = MsgRoomListReq{} }
func (m *MsgRoomListReq) String() string { return proto.CompactTextString(m) }
func (*MsgRoomListReq) ProtoMessage()    {}
func (*MsgRoomListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{2}
}

func (m *MsgRoomListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRoomListReq.Unmarshal(m, b)
}
func (m *MsgRoomListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRoomListReq.Marshal(b, m, deterministic)
}
func (m *MsgRoomListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRoomListReq.Merge(m, src)
}
func (m *MsgRoomListReq) XXX_Size() int {
	return xxx_messageInfo_MsgRoomListReq.Size(m)
}
func (m *MsgRoomListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRoomListReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRoomListReq proto.InternalMessageInfo

func (m *MsgRoomListReq) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

type MsgRoomListRes struct {
	Ret                  ErrCode       `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	RoomList             []*SimpleRoom `protobuf:"bytes,2,rep,name=roomList,proto3" json:"roomList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MsgRoomListRes) Reset()         { *m = MsgRoomListRes{} }
func (m *MsgRoomListRes) String() string { return proto.CompactTextString(m) }
func (*MsgRoomListRes) ProtoMessage()    {}
func (*MsgRoomListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{3}
}

func (m *MsgRoomListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRoomListRes.Unmarshal(m, b)
}
func (m *MsgRoomListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRoomListRes.Marshal(b, m, deterministic)
}
func (m *MsgRoomListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRoomListRes.Merge(m, src)
}
func (m *MsgRoomListRes) XXX_Size() int {
	return xxx_messageInfo_MsgRoomListRes.Size(m)
}
func (m *MsgRoomListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRoomListRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRoomListRes proto.InternalMessageInfo

func (m *MsgRoomListRes) GetRet() ErrCode {
	if m != nil {
		return m.Ret
	}
	return ErrCode_OK
}

func (m *MsgRoomListRes) GetRoomList() []*SimpleRoom {
	if m != nil {
		return m.RoomList
	}
	return nil
}

type MsgAddRoomReq struct {
	RoomUuid             string      `protobuf:"bytes,1,opt,name=RoomUuid,proto3" json:"RoomUuid,omitempty"`
	RoomType             int32       `protobuf:"varint,2,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	PlayerInfo           *PlayerInfo `protobuf:"bytes,3,opt,name=PlayerInfo,proto3" json:"PlayerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MsgAddRoomReq) Reset()         { *m = MsgAddRoomReq{} }
func (m *MsgAddRoomReq) String() string { return proto.CompactTextString(m) }
func (*MsgAddRoomReq) ProtoMessage()    {}
func (*MsgAddRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{4}
}

func (m *MsgAddRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAddRoomReq.Unmarshal(m, b)
}
func (m *MsgAddRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAddRoomReq.Marshal(b, m, deterministic)
}
func (m *MsgAddRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddRoomReq.Merge(m, src)
}
func (m *MsgAddRoomReq) XXX_Size() int {
	return xxx_messageInfo_MsgAddRoomReq.Size(m)
}
func (m *MsgAddRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddRoomReq proto.InternalMessageInfo

func (m *MsgAddRoomReq) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *MsgAddRoomReq) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *MsgAddRoomReq) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type MsgAddRoomRes struct {
	Ret ErrCode `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	//uint64 ClientId = 2;
	Room                 *Room    `protobuf:"bytes,2,opt,name=Room,proto3" json:"Room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAddRoomRes) Reset()         { *m = MsgAddRoomRes{} }
func (m *MsgAddRoomRes) String() string { return proto.CompactTextString(m) }
func (*MsgAddRoomRes) ProtoMessage()    {}
func (*MsgAddRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{5}
}

func (m *MsgAddRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAddRoomRes.Unmarshal(m, b)
}
func (m *MsgAddRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAddRoomRes.Marshal(b, m, deterministic)
}
func (m *MsgAddRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddRoomRes.Merge(m, src)
}
func (m *MsgAddRoomRes) XXX_Size() int {
	return xxx_messageInfo_MsgAddRoomRes.Size(m)
}
func (m *MsgAddRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddRoomRes proto.InternalMessageInfo

func (m *MsgAddRoomRes) GetRet() ErrCode {
	if m != nil {
		return m.Ret
	}
	return ErrCode_OK
}

func (m *MsgAddRoomRes) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

//同步房间已有用户
type MsgClientOnRoomRes struct {
	//repeated PlayerInfo RoomPlayer = 1;
	Room                 *Room    `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClientOnRoomRes) Reset()         { *m = MsgClientOnRoomRes{} }
func (m *MsgClientOnRoomRes) String() string { return proto.CompactTextString(m) }
func (*MsgClientOnRoomRes) ProtoMessage()    {}
func (*MsgClientOnRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{6}
}

func (m *MsgClientOnRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClientOnRoomRes.Unmarshal(m, b)
}
func (m *MsgClientOnRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClientOnRoomRes.Marshal(b, m, deterministic)
}
func (m *MsgClientOnRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClientOnRoomRes.Merge(m, src)
}
func (m *MsgClientOnRoomRes) XXX_Size() int {
	return xxx_messageInfo_MsgClientOnRoomRes.Size(m)
}
func (m *MsgClientOnRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClientOnRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClientOnRoomRes proto.InternalMessageInfo

func (m *MsgClientOnRoomRes) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

type MsgQuitRoomReq struct {
	RoomUuid             string   `protobuf:"bytes,1,opt,name=RoomUuid,proto3" json:"RoomUuid,omitempty"`
	RoomType             int32    `protobuf:"varint,2,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgQuitRoomReq) Reset()         { *m = MsgQuitRoomReq{} }
func (m *MsgQuitRoomReq) String() string { return proto.CompactTextString(m) }
func (*MsgQuitRoomReq) ProtoMessage()    {}
func (*MsgQuitRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{7}
}

func (m *MsgQuitRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgQuitRoomReq.Unmarshal(m, b)
}
func (m *MsgQuitRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgQuitRoomReq.Marshal(b, m, deterministic)
}
func (m *MsgQuitRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQuitRoomReq.Merge(m, src)
}
func (m *MsgQuitRoomReq) XXX_Size() int {
	return xxx_messageInfo_MsgQuitRoomReq.Size(m)
}
func (m *MsgQuitRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQuitRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQuitRoomReq proto.InternalMessageInfo

func (m *MsgQuitRoomReq) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *MsgQuitRoomReq) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

type MsgQuitRoomRes struct {
	Ret                  ErrCode  `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgQuitRoomRes) Reset()         { *m = MsgQuitRoomRes{} }
func (m *MsgQuitRoomRes) String() string { return proto.CompactTextString(m) }
func (*MsgQuitRoomRes) ProtoMessage()    {}
func (*MsgQuitRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{8}
}

func (m *MsgQuitRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgQuitRoomRes.Unmarshal(m, b)
}
func (m *MsgQuitRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgQuitRoomRes.Marshal(b, m, deterministic)
}
func (m *MsgQuitRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQuitRoomRes.Merge(m, src)
}
func (m *MsgQuitRoomRes) XXX_Size() int {
	return xxx_messageInfo_MsgQuitRoomRes.Size(m)
}
func (m *MsgQuitRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQuitRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQuitRoomRes proto.InternalMessageInfo

func (m *MsgQuitRoomRes) GetRet() ErrCode {
	if m != nil {
		return m.Ret
	}
	return ErrCode_OK
}

//移除用户
type MsgRemoveUserReq struct {
	RoomUuid             string   `protobuf:"bytes,1,opt,name=RoomUuid,proto3" json:"RoomUuid,omitempty"`
	RoomType             int32    `protobuf:"varint,2,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	RemoveUserId         uint64   `protobuf:"varint,3,opt,name=RemoveUserId,proto3" json:"RemoveUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRemoveUserReq) Reset()         { *m = MsgRemoveUserReq{} }
func (m *MsgRemoveUserReq) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveUserReq) ProtoMessage()    {}
func (*MsgRemoveUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{9}
}

func (m *MsgRemoveUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRemoveUserReq.Unmarshal(m, b)
}
func (m *MsgRemoveUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRemoveUserReq.Marshal(b, m, deterministic)
}
func (m *MsgRemoveUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveUserReq.Merge(m, src)
}
func (m *MsgRemoveUserReq) XXX_Size() int {
	return xxx_messageInfo_MsgRemoveUserReq.Size(m)
}
func (m *MsgRemoveUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveUserReq proto.InternalMessageInfo

func (m *MsgRemoveUserReq) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *MsgRemoveUserReq) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *MsgRemoveUserReq) GetRemoveUserId() uint64 {
	if m != nil {
		return m.RemoveUserId
	}
	return 0
}

type MsgRemoveUserRes struct {
	Ret                  ErrCode  `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	Room                 *Room    `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRemoveUserRes) Reset()         { *m = MsgRemoveUserRes{} }
func (m *MsgRemoveUserRes) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveUserRes) ProtoMessage()    {}
func (*MsgRemoveUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{10}
}

func (m *MsgRemoveUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRemoveUserRes.Unmarshal(m, b)
}
func (m *MsgRemoveUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRemoveUserRes.Marshal(b, m, deterministic)
}
func (m *MsgRemoveUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveUserRes.Merge(m, src)
}
func (m *MsgRemoveUserRes) XXX_Size() int {
	return xxx_messageInfo_MsgRemoveUserRes.Size(m)
}
func (m *MsgRemoveUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveUserRes proto.InternalMessageInfo

func (m *MsgRemoveUserRes) GetRet() ErrCode {
	if m != nil {
		return m.Ret
	}
	return ErrCode_OK
}

func (m *MsgRemoveUserRes) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

//用户被移除房间回包
type MsgUserRemovedRes struct {
	RoomUuid             string   `protobuf:"bytes,1,opt,name=RoomUuid,proto3" json:"RoomUuid,omitempty"`
	RoomType             int32    `protobuf:"varint,2,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgUserRemovedRes) Reset()         { *m = MsgUserRemovedRes{} }
func (m *MsgUserRemovedRes) String() string { return proto.CompactTextString(m) }
func (*MsgUserRemovedRes) ProtoMessage()    {}
func (*MsgUserRemovedRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{11}
}

func (m *MsgUserRemovedRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUserRemovedRes.Unmarshal(m, b)
}
func (m *MsgUserRemovedRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUserRemovedRes.Marshal(b, m, deterministic)
}
func (m *MsgUserRemovedRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUserRemovedRes.Merge(m, src)
}
func (m *MsgUserRemovedRes) XXX_Size() int {
	return xxx_messageInfo_MsgUserRemovedRes.Size(m)
}
func (m *MsgUserRemovedRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUserRemovedRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUserRemovedRes proto.InternalMessageInfo

func (m *MsgUserRemovedRes) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *MsgUserRemovedRes) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

// uuid string //房间uuid
//roomName string //房间名字
//ownerCid uint64
//roomType int32 //房间类型
//avgRank uint64 //房间平均分数
//roomClientNum int32 //房间人数
//owner *common.PlayerInfo
//otherUsers []*common.PlayerInfo
type Room struct {
	Uuid                 string        `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	RoomName             string        `protobuf:"bytes,2,opt,name=RoomName,proto3" json:"RoomName,omitempty"`
	RoomType             int32         `protobuf:"varint,3,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	AvgRank              uint64        `protobuf:"varint,4,opt,name=AvgRank,proto3" json:"AvgRank,omitempty"`
	RoomClientNum        int32         `protobuf:"varint,5,opt,name=RoomClientNum,proto3" json:"RoomClientNum,omitempty"`
	Owner                *PlayerInfo   `protobuf:"bytes,6,opt,name=Owner,proto3" json:"Owner,omitempty"`
	OtherClients         []*PlayerInfo `protobuf:"bytes,7,rep,name=OtherClients,proto3" json:"OtherClients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{12}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Room) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *Room) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *Room) GetAvgRank() uint64 {
	if m != nil {
		return m.AvgRank
	}
	return 0
}

func (m *Room) GetRoomClientNum() int32 {
	if m != nil {
		return m.RoomClientNum
	}
	return 0
}

func (m *Room) GetOwner() *PlayerInfo {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Room) GetOtherClients() []*PlayerInfo {
	if m != nil {
		return m.OtherClients
	}
	return nil
}

//简化版room数据
type SimpleRoom struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	RoomName             string   `protobuf:"bytes,2,opt,name=RoomName,proto3" json:"RoomName,omitempty"`
	RoomType             int32    `protobuf:"varint,3,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	AvgRank              uint64   `protobuf:"varint,4,opt,name=AvgRank,proto3" json:"AvgRank,omitempty"`
	RoomClientNum        int32    `protobuf:"varint,5,opt,name=RoomClientNum,proto3" json:"RoomClientNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleRoom) Reset()         { *m = SimpleRoom{} }
func (m *SimpleRoom) String() string { return proto.CompactTextString(m) }
func (*SimpleRoom) ProtoMessage()    {}
func (*SimpleRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_56821081eb5e5870, []int{13}
}

func (m *SimpleRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleRoom.Unmarshal(m, b)
}
func (m *SimpleRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleRoom.Marshal(b, m, deterministic)
}
func (m *SimpleRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleRoom.Merge(m, src)
}
func (m *SimpleRoom) XXX_Size() int {
	return xxx_messageInfo_SimpleRoom.Size(m)
}
func (m *SimpleRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleRoom.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleRoom proto.InternalMessageInfo

func (m *SimpleRoom) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SimpleRoom) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *SimpleRoom) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *SimpleRoom) GetAvgRank() uint64 {
	if m != nil {
		return m.AvgRank
	}
	return 0
}

func (m *SimpleRoom) GetRoomClientNum() int32 {
	if m != nil {
		return m.RoomClientNum
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgCreateRoomReq)(nil), "msg.MsgCreateRoomReq")
	proto.RegisterType((*MsgCreateRoomRes)(nil), "msg.MsgCreateRoomRes")
	proto.RegisterType((*MsgRoomListReq)(nil), "msg.MsgRoomListReq")
	proto.RegisterType((*MsgRoomListRes)(nil), "msg.MsgRoomListRes")
	proto.RegisterType((*MsgAddRoomReq)(nil), "msg.MsgAddRoomReq")
	proto.RegisterType((*MsgAddRoomRes)(nil), "msg.MsgAddRoomRes")
	proto.RegisterType((*MsgClientOnRoomRes)(nil), "msg.MsgClientOnRoomRes")
	proto.RegisterType((*MsgQuitRoomReq)(nil), "msg.MsgQuitRoomReq")
	proto.RegisterType((*MsgQuitRoomRes)(nil), "msg.MsgQuitRoomRes")
	proto.RegisterType((*MsgRemoveUserReq)(nil), "msg.MsgRemoveUserReq")
	proto.RegisterType((*MsgRemoveUserRes)(nil), "msg.MsgRemoveUserRes")
	proto.RegisterType((*MsgUserRemovedRes)(nil), "msg.MsgUserRemovedRes")
	proto.RegisterType((*Room)(nil), "msg.Room")
	proto.RegisterType((*SimpleRoom)(nil), "msg.SimpleRoom")
}

func init() { proto.RegisterFile("proto/msgproto/room.proto", fileDescriptor_56821081eb5e5870) }

var fileDescriptor_56821081eb5e5870 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0x5f, 0x6f, 0xd3, 0x30,
	0x10, 0x57, 0x9a, 0x74, 0xdd, 0x8e, 0x6e, 0x80, 0x9f, 0x4c, 0xc5, 0x9f, 0xca, 0x02, 0x69, 0x12,
	0x28, 0x43, 0xeb, 0x23, 0x4f, 0x63, 0x42, 0x62, 0x82, 0xb4, 0xcc, 0xb0, 0x17, 0x24, 0x84, 0x02,
	0xf1, 0x4c, 0x44, 0x1d, 0x07, 0x3b, 0x1d, 0xf4, 0x9b, 0xf0, 0x29, 0xf9, 0x0c, 0xc8, 0x76, 0x9a,
	0x26, 0xa1, 0x22, 0x88, 0xbe, 0xec, 0x25, 0xf2, 0xdd, 0xfd, 0xee, 0x77, 0xbe, 0xdf, 0x9d, 0x03,
	0x77, 0x72, 0x25, 0x0b, 0x79, 0x24, 0x34, 0x77, 0x07, 0x25, 0xa5, 0x08, 0xed, 0x11, 0xf9, 0x42,
	0xf3, 0xd1, 0xdd, 0x56, 0x9c, 0x29, 0xf5, 0x59, 0x26, 0xcc, 0x41, 0x46, 0x0f, 0x5a, 0xd1, 0x7c,
	0x1e, 0x2f, 0x99, 0x4a, 0xb3, 0x4b, 0xe9, 0x00, 0xe4, 0x23, 0xdc, 0x8a, 0x34, 0x3f, 0x55, 0x2c,
	0x2e, 0x18, 0x95, 0x52, 0x50, 0xf6, 0x0d, 0x8d, 0x60, 0xd7, 0x1c, 0xdf, 0x2d, 0x73, 0x86, 0xbd,
	0xb1, 0x77, 0xd8, 0xa7, 0x95, 0x8d, 0x8e, 0x00, 0xde, 0x58, 0x8e, 0xb3, 0xec, 0x52, 0xe2, 0xde,
	0xd8, 0x3b, 0xbc, 0x71, 0x7c, 0x33, 0x14, 0x9a, 0x87, 0x6b, 0x37, 0xad, 0x41, 0xc8, 0xf9, 0x1f,
	0x05, 0x34, 0xba, 0x0f, 0x3e, 0x65, 0x85, 0xe5, 0x3e, 0x38, 0x1e, 0xda, 0xec, 0x17, 0x4a, 0x9d,
	0xca, 0x84, 0x51, 0x13, 0x40, 0xf7, 0x20, 0x30, 0x6d, 0x96, 0xf4, 0x7b, 0x16, 0x60, 0x73, 0xad,
	0x9b, 0x3c, 0x81, 0x83, 0x48, 0x73, 0xe3, 0x78, 0x9d, 0xea, 0xa2, 0xe3, 0xc6, 0xe4, 0x43, 0x0b,
	0xdd, 0x5d, 0xfe, 0x31, 0xec, 0xaa, 0x12, 0x8e, 0x7b, 0x63, 0xbf, 0xea, 0xf0, 0x6d, 0x2a, 0xf2,
	0xb9, 0x6b, 0xa2, 0x02, 0x90, 0x1f, 0xb0, 0x1f, 0x69, 0x7e, 0x92, 0x24, 0x2d, 0xf5, 0x2e, 0x16,
	0x69, 0x62, 0x4b, 0xec, 0xd1, 0xca, 0x6e, 0xdc, 0xb3, 0xf7, 0x57, 0x65, 0xfd, 0x6e, 0x65, 0xa7,
	0xcd, 0xca, 0xff, 0x24, 0x2b, 0xdd, 0x2c, 0xab, 0xf9, 0x92, 0x09, 0x20, 0x33, 0xa9, 0x79, 0xca,
	0xb2, 0x62, 0x96, 0xad, 0x48, 0x57, 0xb3, 0xf0, 0x36, 0xcf, 0xe2, 0xa5, 0x55, 0xf7, 0x7c, 0x91,
	0x16, 0x5b, 0xf6, 0x4f, 0x9e, 0xb6, 0x98, 0x3a, 0xfb, 0x21, 0x99, 0x5d, 0x2d, 0xca, 0x84, 0xbc,
	0x62, 0x17, 0x9a, 0xa9, 0x6d, 0xd4, 0x27, 0x30, 0x5c, 0x13, 0x9d, 0x25, 0x56, 0xff, 0x80, 0x36,
	0x7c, 0xe5, 0x2a, 0xd7, 0xeb, 0x6d, 0xbd, 0xca, 0xaf, 0xe0, 0x76, 0xa4, 0xb9, 0x23, 0x33, 0xb4,
	0x89, 0xe1, 0xfc, 0x5f, 0x05, 0x7f, 0x79, 0x6e, 0xc0, 0x08, 0x41, 0x50, 0x4b, 0x0e, 0xea, 0x89,
	0xd3, 0x58, 0xb8, 0xc4, 0x92, 0xd4, 0xd8, 0x0d, 0x52, 0xbf, 0x25, 0x0c, 0x86, 0xc1, 0xc9, 0x15,
	0xa7, 0x71, 0xf6, 0x15, 0x07, 0x56, 0x93, 0x95, 0x89, 0x1e, 0xc2, 0xbe, 0x41, 0xb9, 0x85, 0x99,
	0x2e, 0x04, 0xee, 0xdb, 0xd4, 0xa6, 0x13, 0x3d, 0x82, 0xfe, 0xec, 0x7b, 0xc6, 0x14, 0xde, 0xd9,
	0xbc, 0xd1, 0x2e, 0x8a, 0x26, 0x30, 0x9c, 0x15, 0x5f, 0x98, 0x72, 0x89, 0x1a, 0x0f, 0x6a, 0xef,
	0xae, 0x86, 0x6e, 0x80, 0xc8, 0x4f, 0x0f, 0x60, 0xfd, 0x28, 0xaf, 0x53, 0xdb, 0xcf, 0x07, 0xef,
	0xfb, 0xe1, 0x33, 0xa1, 0xf9, 0xa7, 0x1d, 0xfb, 0x9f, 0x9d, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0x22, 0x99, 0x02, 0x9a, 0xc8, 0x05, 0x00, 0x00,
}
