// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/msgproto/table.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgAddTableReq struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	TableUuid            string   `protobuf:"bytes,2,opt,name=TableUuid,proto3" json:"TableUuid,omitempty"`
	Flag                 int32    `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAddTableReq) Reset()         { *m = MsgAddTableReq{} }
func (m *MsgAddTableReq) String() string { return proto.CompactTextString(m) }
func (*MsgAddTableReq) ProtoMessage()    {}
func (*MsgAddTableReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cf7e9aa369046db, []int{0}
}

func (m *MsgAddTableReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAddTableReq.Unmarshal(m, b)
}
func (m *MsgAddTableReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAddTableReq.Marshal(b, m, deterministic)
}
func (m *MsgAddTableReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddTableReq.Merge(m, src)
}
func (m *MsgAddTableReq) XXX_Size() int {
	return xxx_messageInfo_MsgAddTableReq.Size(m)
}
func (m *MsgAddTableReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddTableReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddTableReq proto.InternalMessageInfo

func (m *MsgAddTableReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MsgAddTableReq) GetTableUuid() string {
	if m != nil {
		return m.TableUuid
	}
	return ""
}

func (m *MsgAddTableReq) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

type MsgAddTableRes struct {
	Ret                  ErrCode  `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAddTableRes) Reset()         { *m = MsgAddTableRes{} }
func (m *MsgAddTableRes) String() string { return proto.CompactTextString(m) }
func (*MsgAddTableRes) ProtoMessage()    {}
func (*MsgAddTableRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cf7e9aa369046db, []int{1}
}

func (m *MsgAddTableRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAddTableRes.Unmarshal(m, b)
}
func (m *MsgAddTableRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAddTableRes.Marshal(b, m, deterministic)
}
func (m *MsgAddTableRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddTableRes.Merge(m, src)
}
func (m *MsgAddTableRes) XXX_Size() int {
	return xxx_messageInfo_MsgAddTableRes.Size(m)
}
func (m *MsgAddTableRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddTableRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddTableRes proto.InternalMessageInfo

func (m *MsgAddTableRes) GetRet() ErrCode {
	if m != nil {
		return m.Ret
	}
	return ErrCode_OK
}

type MsgClientConnectedStatusRes struct {
	Ret                  ErrCode  `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClientConnectedStatusRes) Reset()         { *m = MsgClientConnectedStatusRes{} }
func (m *MsgClientConnectedStatusRes) String() string { return proto.CompactTextString(m) }
func (*MsgClientConnectedStatusRes) ProtoMessage()    {}
func (*MsgClientConnectedStatusRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cf7e9aa369046db, []int{2}
}

func (m *MsgClientConnectedStatusRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClientConnectedStatusRes.Unmarshal(m, b)
}
func (m *MsgClientConnectedStatusRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClientConnectedStatusRes.Marshal(b, m, deterministic)
}
func (m *MsgClientConnectedStatusRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClientConnectedStatusRes.Merge(m, src)
}
func (m *MsgClientConnectedStatusRes) XXX_Size() int {
	return xxx_messageInfo_MsgClientConnectedStatusRes.Size(m)
}
func (m *MsgClientConnectedStatusRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClientConnectedStatusRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClientConnectedStatusRes proto.InternalMessageInfo

func (m *MsgClientConnectedStatusRes) GetRet() ErrCode {
	if m != nil {
		return m.Ret
	}
	return ErrCode_OK
}

type MsgCreateTableReq struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	GameTypeId           int32    `protobuf:"varint,2,opt,name=GameTypeId,proto3" json:"GameTypeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateTableReq) Reset()         { *m = MsgCreateTableReq{} }
func (m *MsgCreateTableReq) String() string { return proto.CompactTextString(m) }
func (*MsgCreateTableReq) ProtoMessage()    {}
func (*MsgCreateTableReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cf7e9aa369046db, []int{3}
}

func (m *MsgCreateTableReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateTableReq.Unmarshal(m, b)
}
func (m *MsgCreateTableReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateTableReq.Marshal(b, m, deterministic)
}
func (m *MsgCreateTableReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateTableReq.Merge(m, src)
}
func (m *MsgCreateTableReq) XXX_Size() int {
	return xxx_messageInfo_MsgCreateTableReq.Size(m)
}
func (m *MsgCreateTableReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateTableReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateTableReq proto.InternalMessageInfo

func (m *MsgCreateTableReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MsgCreateTableReq) GetGameTypeId() int32 {
	if m != nil {
		return m.GameTypeId
	}
	return 0
}

type MsgCreateTableRes struct {
	TableList            []*TableGeneral `protobuf:"bytes,1,rep,name=tableList,proto3" json:"tableList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MsgCreateTableRes) Reset()         { *m = MsgCreateTableRes{} }
func (m *MsgCreateTableRes) String() string { return proto.CompactTextString(m) }
func (*MsgCreateTableRes) ProtoMessage()    {}
func (*MsgCreateTableRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cf7e9aa369046db, []int{4}
}

func (m *MsgCreateTableRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateTableRes.Unmarshal(m, b)
}
func (m *MsgCreateTableRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateTableRes.Marshal(b, m, deterministic)
}
func (m *MsgCreateTableRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateTableRes.Merge(m, src)
}
func (m *MsgCreateTableRes) XXX_Size() int {
	return xxx_messageInfo_MsgCreateTableRes.Size(m)
}
func (m *MsgCreateTableRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateTableRes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateTableRes proto.InternalMessageInfo

func (m *MsgCreateTableRes) GetTableList() []*TableGeneral {
	if m != nil {
		return m.TableList
	}
	return nil
}

//对局桌子简约版
type TableGeneral struct {
	GameTypeId           int32         `protobuf:"varint,1,opt,name=GameTypeId,proto3" json:"GameTypeId,omitempty"`
	PlayList             []*PlayerInfo `protobuf:"bytes,2,rep,name=playList,proto3" json:"playList,omitempty"`
	MatchNum             int32         `protobuf:"varint,3,opt,name=MatchNum,proto3" json:"MatchNum,omitempty"`
	TableIdUuid          uint64        `protobuf:"varint,4,opt,name=tableIdUuid,proto3" json:"tableIdUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TableGeneral) Reset()         { *m = TableGeneral{} }
func (m *TableGeneral) String() string { return proto.CompactTextString(m) }
func (*TableGeneral) ProtoMessage()    {}
func (*TableGeneral) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cf7e9aa369046db, []int{5}
}

func (m *TableGeneral) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableGeneral.Unmarshal(m, b)
}
func (m *TableGeneral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableGeneral.Marshal(b, m, deterministic)
}
func (m *TableGeneral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableGeneral.Merge(m, src)
}
func (m *TableGeneral) XXX_Size() int {
	return xxx_messageInfo_TableGeneral.Size(m)
}
func (m *TableGeneral) XXX_DiscardUnknown() {
	xxx_messageInfo_TableGeneral.DiscardUnknown(m)
}

var xxx_messageInfo_TableGeneral proto.InternalMessageInfo

func (m *TableGeneral) GetGameTypeId() int32 {
	if m != nil {
		return m.GameTypeId
	}
	return 0
}

func (m *TableGeneral) GetPlayList() []*PlayerInfo {
	if m != nil {
		return m.PlayList
	}
	return nil
}

func (m *TableGeneral) GetMatchNum() int32 {
	if m != nil {
		return m.MatchNum
	}
	return 0
}

func (m *TableGeneral) GetTableIdUuid() uint64 {
	if m != nil {
		return m.TableIdUuid
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgAddTableReq)(nil), "msg.MsgAddTableReq")
	proto.RegisterType((*MsgAddTableRes)(nil), "msg.MsgAddTableRes")
	proto.RegisterType((*MsgClientConnectedStatusRes)(nil), "msg.MsgClientConnectedStatusRes")
	proto.RegisterType((*MsgCreateTableReq)(nil), "msg.MsgCreateTableReq")
	proto.RegisterType((*MsgCreateTableRes)(nil), "msg.MsgCreateTableRes")
	proto.RegisterType((*TableGeneral)(nil), "msg.TableGeneral")
}

func init() { proto.RegisterFile("proto/msgproto/table.proto", fileDescriptor_6cf7e9aa369046db) }

var fileDescriptor_6cf7e9aa369046db = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6b, 0xea, 0x40,
	0x14, 0x25, 0x46, 0x7d, 0x7a, 0x15, 0x1f, 0xce, 0xe2, 0x21, 0x79, 0x62, 0x43, 0x56, 0x81, 0x42,
	0x2c, 0x76, 0x59, 0xba, 0x68, 0x6d, 0x91, 0xd0, 0x5a, 0xca, 0x54, 0x37, 0xee, 0x46, 0xe7, 0x9a,
	0x06, 0xf2, 0x61, 0x67, 0xc6, 0x85, 0x3f, 0xa5, 0xff, 0xb6, 0xe4, 0x2a, 0x2a, 0xe9, 0xa2, 0xdd,
	0xdd, 0x8f, 0x73, 0xcf, 0xb9, 0x77, 0xce, 0x80, 0xb3, 0x51, 0xb9, 0xc9, 0x87, 0xa9, 0x8e, 0xf6,
	0x81, 0x11, 0xcb, 0x04, 0x03, 0x8a, 0x99, 0x9d, 0xea, 0xc8, 0xe9, 0x97, 0x00, 0xa8, 0xd4, 0x2a,
	0x97, 0x07, 0x88, 0x73, 0x51, 0xea, 0x6e, 0x12, 0xb1, 0x43, 0x15, 0x67, 0xeb, 0x7c, 0x0f, 0xf0,
	0x16, 0xd0, 0x99, 0xea, 0xe8, 0x4e, 0xca, 0x59, 0x41, 0xcc, 0xf1, 0x83, 0xfd, 0x83, 0xfa, 0x5c,
	0xa3, 0x0a, 0x65, 0xcf, 0x72, 0x2d, 0xbf, 0xca, 0x0f, 0x19, 0xeb, 0x43, 0x93, 0x30, 0xf3, 0x6d,
	0x2c, 0x7b, 0x15, 0xd7, 0xf2, 0x9b, 0xfc, 0x54, 0x60, 0x0c, 0xaa, 0xeb, 0x44, 0x44, 0x3d, 0xdb,
	0xb5, 0xfc, 0x1a, 0xa7, 0xd8, 0xbb, 0x2a, 0x71, 0x6b, 0x36, 0x00, 0x9b, 0xa3, 0x21, 0xe2, 0xce,
	0xa8, 0x1d, 0xa4, 0x3a, 0x0a, 0x1e, 0x95, 0x1a, 0xe7, 0x12, 0x79, 0xd1, 0xf0, 0x6e, 0xe1, 0xff,
	0x54, 0x47, 0xe3, 0x24, 0xc6, 0xcc, 0x8c, 0xf3, 0x2c, 0xc3, 0x95, 0x41, 0xf9, 0x66, 0x84, 0xd9,
	0xea, 0xdf, 0x8c, 0x3f, 0x41, 0xb7, 0x18, 0x57, 0x28, 0x0c, 0xfe, 0x78, 0xcf, 0x00, 0x60, 0x22,
	0x52, 0x9c, 0xed, 0x36, 0x18, 0xee, 0x0f, 0xaa, 0xf1, 0xb3, 0x8a, 0xf7, 0xf0, 0x9d, 0x4c, 0xb3,
	0x21, 0x34, 0xc9, 0x81, 0xe7, 0x58, 0x17, 0x7b, 0xd8, 0x7e, 0x6b, 0xd4, 0xa5, 0x3d, 0x08, 0x31,
	0xc1, 0x0c, 0x95, 0x48, 0xf8, 0x09, 0xe3, 0x7d, 0x5a, 0xd0, 0x3e, 0xef, 0x95, 0x64, 0xad, 0xb2,
	0x2c, 0xbb, 0x84, 0x46, 0x61, 0x12, 0x09, 0x54, 0x48, 0xe0, 0x2f, 0x09, 0xbc, 0x92, 0x73, 0x61,
	0xb6, 0xce, 0xf9, 0x11, 0xc0, 0x1c, 0x68, 0x4c, 0x85, 0x59, 0xbd, 0xbf, 0x6c, 0xd3, 0xc3, 0xcb,
	0x1f, 0x73, 0xe6, 0x42, 0x8b, 0xd6, 0x08, 0x25, 0x39, 0x56, 0xa5, 0xe3, 0xcf, 0x4b, 0xf7, 0x7f,
	0x16, 0xb5, 0xe0, 0x26, 0xd5, 0xd1, 0xb2, 0x4e, 0x7f, 0xe1, 0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff,
	0xe3, 0x1f, 0x50, 0x4d, 0x6d, 0x02, 0x00, 0x00,
}
