// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rpcproto/base.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Int struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int) Reset()         { *m = Int{} }
func (m *Int) String() string { return proto.CompactTextString(m) }
func (*Int) ProtoMessage()    {}
func (*Int) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b82c7de48e7530d, []int{0}
}

func (m *Int) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int.Unmarshal(m, b)
}
func (m *Int) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int.Marshal(b, m, deterministic)
}
func (m *Int) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int.Merge(m, src)
}
func (m *Int) XXX_Size() int {
	return xxx_messageInfo_Int.Size(m)
}
func (m *Int) XXX_DiscardUnknown() {
	xxx_messageInfo_Int.DiscardUnknown(m)
}

var xxx_messageInfo_Int proto.InternalMessageInfo

func (m *Int) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Int64 struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64) Reset()         { *m = Int64{} }
func (m *Int64) String() string { return proto.CompactTextString(m) }
func (*Int64) ProtoMessage()    {}
func (*Int64) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b82c7de48e7530d, []int{1}
}

func (m *Int64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64.Unmarshal(m, b)
}
func (m *Int64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64.Marshal(b, m, deterministic)
}
func (m *Int64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64.Merge(m, src)
}
func (m *Int64) XXX_Size() int {
	return xxx_messageInfo_Int64.Size(m)
}
func (m *Int64) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64.DiscardUnknown(m)
}

var xxx_messageInfo_Int64 proto.InternalMessageInfo

func (m *Int64) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Bool struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b82c7de48e7530d, []int{2}
}

func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (m *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(m, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type String struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b82c7de48e7530d, []int{3}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Bytes struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bytes) Reset()         { *m = Bytes{} }
func (m *Bytes) String() string { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()    {}
func (*Bytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b82c7de48e7530d, []int{4}
}

func (m *Bytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bytes.Unmarshal(m, b)
}
func (m *Bytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bytes.Marshal(b, m, deterministic)
}
func (m *Bytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bytes.Merge(m, src)
}
func (m *Bytes) XXX_Size() int {
	return xxx_messageInfo_Bytes.Size(m)
}
func (m *Bytes) XXX_DiscardUnknown() {
	xxx_messageInfo_Bytes.DiscardUnknown(m)
}

var xxx_messageInfo_Bytes proto.InternalMessageInfo

func (m *Bytes) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PlaceHolders struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceHolders) Reset()         { *m = PlaceHolders{} }
func (m *PlaceHolders) String() string { return proto.CompactTextString(m) }
func (*PlaceHolders) ProtoMessage()    {}
func (*PlaceHolders) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b82c7de48e7530d, []int{5}
}

func (m *PlaceHolders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceHolders.Unmarshal(m, b)
}
func (m *PlaceHolders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceHolders.Marshal(b, m, deterministic)
}
func (m *PlaceHolders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceHolders.Merge(m, src)
}
func (m *PlaceHolders) XXX_Size() int {
	return xxx_messageInfo_PlaceHolders.Size(m)
}
func (m *PlaceHolders) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceHolders.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceHolders proto.InternalMessageInfo

//邮件结构
type UserMailInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	MailType             int32    `protobuf:"varint,2,opt,name=MailType,proto3" json:"MailType,omitempty"`
	FromUser             uint64   `protobuf:"varint,3,opt,name=FromUser,proto3" json:"FromUser,omitempty"`
	SendToUser           uint64   `protobuf:"varint,4,opt,name=SendToUser,proto3" json:"SendToUser,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=Content,proto3" json:"Content,omitempty"`
	SendTime             int64    `protobuf:"varint,7,opt,name=SendTime,proto3" json:"SendTime,omitempty"`
	Status               int32    `protobuf:"varint,8,opt,name=Status,proto3" json:"Status,omitempty"`
	Attachment           []byte   `protobuf:"bytes,9,opt,name=Attachment,proto3" json:"Attachment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMailInfo) Reset()         { *m = UserMailInfo{} }
func (m *UserMailInfo) String() string { return proto.CompactTextString(m) }
func (*UserMailInfo) ProtoMessage()    {}
func (*UserMailInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b82c7de48e7530d, []int{6}
}

func (m *UserMailInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMailInfo.Unmarshal(m, b)
}
func (m *UserMailInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMailInfo.Marshal(b, m, deterministic)
}
func (m *UserMailInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMailInfo.Merge(m, src)
}
func (m *UserMailInfo) XXX_Size() int {
	return xxx_messageInfo_UserMailInfo.Size(m)
}
func (m *UserMailInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMailInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserMailInfo proto.InternalMessageInfo

func (m *UserMailInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserMailInfo) GetMailType() int32 {
	if m != nil {
		return m.MailType
	}
	return 0
}

func (m *UserMailInfo) GetFromUser() uint64 {
	if m != nil {
		return m.FromUser
	}
	return 0
}

func (m *UserMailInfo) GetSendToUser() uint64 {
	if m != nil {
		return m.SendToUser
	}
	return 0
}

func (m *UserMailInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UserMailInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UserMailInfo) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *UserMailInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserMailInfo) GetAttachment() []byte {
	if m != nil {
		return m.Attachment
	}
	return nil
}

type PlayerInfo struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Rank                 uint64   `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Sex                  int32    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ClientId             uint64   `protobuf:"varint,6,opt,name=clientId,proto3" json:"clientId,omitempty"`
	IsOwner              bool     `protobuf:"varint,7,opt,name=isOwner,proto3" json:"isOwner,omitempty"`
	SeatNum              int32    `protobuf:"varint,8,opt,name=seatNum,proto3" json:"seatNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b82c7de48e7530d, []int{7}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PlayerInfo) GetRank() uint64 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *PlayerInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *PlayerInfo) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *PlayerInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *PlayerInfo) GetClientId() uint64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *PlayerInfo) GetIsOwner() bool {
	if m != nil {
		return m.IsOwner
	}
	return false
}

func (m *PlayerInfo) GetSeatNum() int32 {
	if m != nil {
		return m.SeatNum
	}
	return 0
}

type Room struct {
	Uuid                 string        `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	RoomName             string        `protobuf:"bytes,2,opt,name=RoomName,proto3" json:"RoomName,omitempty"`
	RoomType             int32         `protobuf:"varint,3,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	AvgRank              uint64        `protobuf:"varint,4,opt,name=AvgRank,proto3" json:"AvgRank,omitempty"`
	RoomClientNum        int32         `protobuf:"varint,5,opt,name=RoomClientNum,proto3" json:"RoomClientNum,omitempty"`
	Owner                *PlayerInfo   `protobuf:"bytes,6,opt,name=Owner,proto3" json:"Owner,omitempty"`
	OtherClients         []*PlayerInfo `protobuf:"bytes,7,rep,name=OtherClients,proto3" json:"OtherClients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b82c7de48e7530d, []int{8}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Room) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *Room) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *Room) GetAvgRank() uint64 {
	if m != nil {
		return m.AvgRank
	}
	return 0
}

func (m *Room) GetRoomClientNum() int32 {
	if m != nil {
		return m.RoomClientNum
	}
	return 0
}

func (m *Room) GetOwner() *PlayerInfo {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Room) GetOtherClients() []*PlayerInfo {
	if m != nil {
		return m.OtherClients
	}
	return nil
}

func init() {
	proto.RegisterType((*Int)(nil), "Int")
	proto.RegisterType((*Int64)(nil), "Int64")
	proto.RegisterType((*Bool)(nil), "Bool")
	proto.RegisterType((*String)(nil), "String")
	proto.RegisterType((*Bytes)(nil), "Bytes")
	proto.RegisterType((*PlaceHolders)(nil), "PlaceHolders")
	proto.RegisterType((*UserMailInfo)(nil), "UserMailInfo")
	proto.RegisterType((*PlayerInfo)(nil), "PlayerInfo")
	proto.RegisterType((*Room)(nil), "Room")
}

func init() { proto.RegisterFile("proto/rpcproto/base.proto", fileDescriptor_1b82c7de48e7530d) }

var fileDescriptor_1b82c7de48e7530d = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x93, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0x95, 0x4d, 0xb2, 0x7f, 0xa6, 0x4b, 0x85, 0x2c, 0x54, 0x85, 0x7f, 0xd5, 0x12, 0x71,
	0xe8, 0x69, 0x2b, 0x01, 0xe2, 0xc2, 0xa9, 0x5b, 0x09, 0x91, 0x03, 0x6d, 0xe5, 0x6e, 0x2f, 0xdc,
	0xdc, 0xc4, 0xb4, 0xd1, 0x26, 0xf6, 0xca, 0x76, 0x16, 0xf6, 0x25, 0x79, 0x0c, 0x1e, 0x82, 0x13,
	0x9a, 0x49, 0x1c, 0x36, 0xdc, 0xe6, 0xe7, 0x2f, 0x1e, 0x7f, 0xdf, 0x8c, 0x02, 0xcf, 0xb7, 0x46,
	0x3b, 0x7d, 0x6e, 0xb6, 0x79, 0x5b, 0xdc, 0x0b, 0x2b, 0x97, 0x54, 0xa6, 0x2f, 0x21, 0xcc, 0x94,
	0x63, 0xcf, 0x20, 0xde, 0x89, 0xaa, 0x91, 0x49, 0xb0, 0x08, 0xce, 0x62, 0xde, 0x42, 0xfa, 0x1a,
	0xe2, 0x4c, 0xb9, 0x8f, 0x1f, 0x86, 0x72, 0xe8, 0xe5, 0x57, 0x10, 0xad, 0xb4, 0xae, 0x86, 0xea,
	0xd4, 0xab, 0xa7, 0x30, 0xbe, 0x75, 0xa6, 0x54, 0x0f, 0x43, 0x7d, 0x76, 0xd0, 0x7c, 0xb5, 0x77,
	0xd2, 0x0e, 0xe5, 0xb9, 0x97, 0x8f, 0x61, 0x7e, 0x53, 0x89, 0x5c, 0x7e, 0xd1, 0x55, 0x21, 0x8d,
	0x4d, 0xff, 0x04, 0x30, 0xbf, 0xb3, 0xd2, 0x7c, 0x15, 0x65, 0x95, 0xa9, 0xef, 0x9a, 0x1d, 0xc3,
	0x28, 0x2b, 0xba, 0x96, 0xa3, 0xac, 0x60, 0x2f, 0x60, 0x8a, 0xda, 0x7a, 0xbf, 0x95, 0xc9, 0x88,
	0x52, 0xf4, 0x8c, 0xda, 0x67, 0xa3, 0x6b, 0xbc, 0x9f, 0x84, 0x8b, 0xe0, 0x2c, 0xe2, 0x3d, 0xb3,
	0x53, 0x80, 0x5b, 0xa9, 0x8a, 0xb5, 0x26, 0x35, 0x22, 0xf5, 0xe0, 0x04, 0xed, 0xad, 0x4b, 0x57,
	0xc9, 0x24, 0x6e, 0xdd, 0x13, 0xb0, 0x04, 0x26, 0x97, 0x5a, 0x39, 0xa9, 0x5c, 0x32, 0xa6, 0x73,
	0x8f, 0xf8, 0x16, 0xdd, 0x2e, 0x6b, 0x99, 0x4c, 0x68, 0x5c, 0x3d, 0xb3, 0x13, 0x9c, 0x89, 0x70,
	0x8d, 0x4d, 0xa6, 0xe4, 0xb0, 0x23, 0xf4, 0x70, 0xe1, 0x9c, 0xc8, 0x1f, 0x6b, 0x6c, 0x38, 0xa3,
	0x39, 0x1c, 0x9c, 0xa4, 0xbf, 0x02, 0x80, 0x9b, 0x4a, 0xec, 0xa5, 0xa1, 0xe8, 0x27, 0x30, 0x6e,
	0xac, 0x34, 0x5d, 0xfc, 0x88, 0x77, 0xc4, 0x18, 0x44, 0x46, 0xa8, 0x0d, 0xc5, 0x8f, 0x38, 0xd5,
	0x68, 0x47, 0x95, 0xf9, 0xe6, 0x4a, 0xd4, 0x92, 0xa2, 0xcf, 0x78, 0xcf, 0xec, 0x29, 0x84, 0x56,
	0xfe, 0xa4, 0xcc, 0x31, 0xc7, 0x12, 0x3b, 0x8b, 0x9d, 0x70, 0xc2, 0x74, 0x69, 0x3b, 0xc2, 0x2e,
	0x79, 0x55, 0x4a, 0xe5, 0xb2, 0x82, 0xf2, 0x46, 0xbc, 0x67, 0x1c, 0x45, 0x69, 0xaf, 0x7f, 0x28,
	0x69, 0x28, 0xef, 0x94, 0x7b, 0x44, 0xc5, 0x4a, 0xe1, 0xae, 0x9a, 0xba, 0xcb, 0xeb, 0x31, 0xfd,
	0x1d, 0x40, 0xc4, 0xb5, 0xae, 0xd1, 0xf2, 0x5d, 0x53, 0xfa, 0x3d, 0x52, 0x8d, 0x8f, 0xa1, 0x46,
	0x96, 0x47, 0xad, 0x65, 0xcf, 0x5e, 0xa3, 0x2d, 0x87, 0xed, 0x96, 0x3d, 0xe3, 0x73, 0x17, 0xbb,
	0x07, 0x8e, 0x13, 0x68, 0xd7, 0xe8, 0x91, 0xbd, 0x85, 0x27, 0xf8, 0xd5, 0x25, 0x59, 0x46, 0x3b,
	0x31, 0x5d, 0x1d, 0x1e, 0xb2, 0x37, 0x10, 0xb7, 0x31, 0x30, 0xe1, 0xd1, 0xbb, 0xa3, 0xe5, 0xbf,
	0x91, 0xf3, 0x56, 0x61, 0xe7, 0x30, 0xbf, 0x76, 0x8f, 0xd2, 0xb4, 0x97, 0x6c, 0x32, 0x59, 0x84,
	0xff, 0x7f, 0x39, 0xf8, 0x60, 0x35, 0xf9, 0x16, 0x2f, 0x3f, 0x99, 0x6d, 0x7e, 0x3f, 0xa6, 0xff,
	0xed, 0xfd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xca, 0x43, 0x8b, 0x6e, 0x8c, 0x03, 0x00, 0x00,
}
