// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rpcproto/helper.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//向各个服发送配置重新加载
type ReloadCfgInfo struct {
	FileNameList         []string `protobuf:"bytes,1,rep,name=fileNameList,proto3" json:"fileNameList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReloadCfgInfo) Reset()         { *m = ReloadCfgInfo{} }
func (m *ReloadCfgInfo) String() string { return proto.CompactTextString(m) }
func (*ReloadCfgInfo) ProtoMessage()    {}
func (*ReloadCfgInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa35dbb205cd3fdd, []int{0}
}

func (m *ReloadCfgInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReloadCfgInfo.Unmarshal(m, b)
}
func (m *ReloadCfgInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReloadCfgInfo.Marshal(b, m, deterministic)
}
func (m *ReloadCfgInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReloadCfgInfo.Merge(m, src)
}
func (m *ReloadCfgInfo) XXX_Size() int {
	return xxx_messageInfo_ReloadCfgInfo.Size(m)
}
func (m *ReloadCfgInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReloadCfgInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReloadCfgInfo proto.InternalMessageInfo

func (m *ReloadCfgInfo) GetFileNameList() []string {
	if m != nil {
		return m.FileNameList
	}
	return nil
}

//向各个服发送配置重新加载返回
type ReloadCfgResult struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReloadCfgResult) Reset()         { *m = ReloadCfgResult{} }
func (m *ReloadCfgResult) String() string { return proto.CompactTextString(m) }
func (*ReloadCfgResult) ProtoMessage()    {}
func (*ReloadCfgResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa35dbb205cd3fdd, []int{1}
}

func (m *ReloadCfgResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReloadCfgResult.Unmarshal(m, b)
}
func (m *ReloadCfgResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReloadCfgResult.Marshal(b, m, deterministic)
}
func (m *ReloadCfgResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReloadCfgResult.Merge(m, src)
}
func (m *ReloadCfgResult) XXX_Size() int {
	return xxx_messageInfo_ReloadCfgResult.Size(m)
}
func (m *ReloadCfgResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ReloadCfgResult.DiscardUnknown(m)
}

var xxx_messageInfo_ReloadCfgResult proto.InternalMessageInfo

func (m *ReloadCfgResult) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*ReloadCfgInfo)(nil), "rpc.ReloadCfgInfo")
	proto.RegisterType((*ReloadCfgResult)(nil), "rpc.ReloadCfgResult")
}

func init() { proto.RegisterFile("proto/rpcproto/helper.proto", fileDescriptor_fa35dbb205cd3fdd) }

var fileDescriptor_fa35dbb205cd3fdd = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2a, 0x48, 0x86, 0x30, 0x32, 0x52, 0x73, 0x0a, 0x52, 0x8b, 0xf4, 0xc0, 0x1c,
	0x21, 0xe6, 0xa2, 0x82, 0x64, 0x25, 0x63, 0x2e, 0xde, 0xa0, 0xd4, 0x9c, 0xfc, 0xc4, 0x14, 0xe7,
	0xb4, 0x74, 0xcf, 0xbc, 0xb4, 0x7c, 0x21, 0x25, 0x2e, 0x9e, 0xb4, 0xcc, 0x9c, 0x54, 0xbf, 0xc4,
	0xdc, 0x54, 0x9f, 0xcc, 0xe2, 0x12, 0x09, 0x46, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x14, 0x31, 0x25,
	0x4d, 0x2e, 0x7e, 0xb8, 0xa6, 0xa0, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0x21, 0x31, 0x2e, 0xb6, 0xe2,
	0x92, 0xc4, 0x92, 0xd2, 0x62, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xde, 0x20, 0x28, 0xcf, 0x89, 0x3d,
	0x8a, 0x55, 0xcf, 0xba, 0xa8, 0x20, 0x39, 0x89, 0x0d, 0x6c, 0xa9, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x2f, 0x7b, 0x3b, 0xea, 0x93, 0x00, 0x00, 0x00,
}
