// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rpcproto/login.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginStatus int32

const (
	LoginStatus_LoginStart LoginStatus = 0
	LoginStatus_Logining   LoginStatus = 1
	LoginStatus_Logined    LoginStatus = 2
	LoginStatus_LoginOut   LoginStatus = 3
)

var LoginStatus_name = map[int32]string{
	0: "LoginStart",
	1: "Logining",
	2: "Logined",
	3: "LoginOut",
}

var LoginStatus_value = map[string]int32{
	"LoginStart": 0,
	"Logining":   1,
	"Logined":    2,
	"LoginOut":   3,
}

func (x LoginStatus) String() string {
	return proto.EnumName(LoginStatus_name, int32(x))
}

func (LoginStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b916dfaff5dc64ee, []int{0}
}

type LoginType int32

const (
	LoginType_Gust          LoginType = 0
	LoginType_Account       LoginType = 1
	LoginType_Facebook      LoginType = 2
	LoginType_Google        LoginType = 3
	LoginType_LoginType_Max LoginType = 4
)

var LoginType_name = map[int32]string{
	0: "Gust",
	1: "Account",
	2: "Facebook",
	3: "Google",
	4: "LoginType_Max",
}

var LoginType_value = map[string]int32{
	"Gust":          0,
	"Account":       1,
	"Facebook":      2,
	"Google":        3,
	"LoginType_Max": 4,
}

func (x LoginType) String() string {
	return proto.EnumName(LoginType_name, int32(x))
}

func (LoginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b916dfaff5dc64ee, []int{1}
}

//向数据库请求登陆
type LoginInfo struct {
	PlatType             LoginType `protobuf:"varint,1,opt,name=PlatType,proto3,enum=rpc.LoginType" json:"PlatType,omitempty"`
	PlatId               string    `protobuf:"bytes,2,opt,name=PlatId,proto3" json:"PlatId,omitempty"`
	AccessToken          string    `protobuf:"bytes,3,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	PassWord             string    `protobuf:"bytes,4,opt,name=PassWord,proto3" json:"PassWord,omitempty"`
	Account              string    `protobuf:"bytes,5,opt,name=Account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginInfo) Reset()         { *m = LoginInfo{} }
func (m *LoginInfo) String() string { return proto.CompactTextString(m) }
func (*LoginInfo) ProtoMessage()    {}
func (*LoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b916dfaff5dc64ee, []int{0}
}

func (m *LoginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginInfo.Unmarshal(m, b)
}
func (m *LoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginInfo.Marshal(b, m, deterministic)
}
func (m *LoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfo.Merge(m, src)
}
func (m *LoginInfo) XXX_Size() int {
	return xxx_messageInfo_LoginInfo.Size(m)
}
func (m *LoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfo proto.InternalMessageInfo

func (m *LoginInfo) GetPlatType() LoginType {
	if m != nil {
		return m.PlatType
	}
	return LoginType_Gust
}

func (m *LoginInfo) GetPlatId() string {
	if m != nil {
		return m.PlatId
	}
	return ""
}

func (m *LoginInfo) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginInfo) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *LoginInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

//数据库返回结果
type LoginResult struct {
	PlatType             LoginType `protobuf:"varint,1,opt,name=PlatType,proto3,enum=rpc.LoginType" json:"PlatType,omitempty"`
	PlatId               string    `protobuf:"bytes,2,opt,name=PlatId,proto3" json:"PlatId,omitempty"`
	AccessToken          string    `protobuf:"bytes,3,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	Ret                  int32     `protobuf:"varint,4,opt,name=Ret,proto3" json:"Ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginResult) Reset()         { *m = LoginResult{} }
func (m *LoginResult) String() string { return proto.CompactTextString(m) }
func (*LoginResult) ProtoMessage()    {}
func (*LoginResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b916dfaff5dc64ee, []int{1}
}

func (m *LoginResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResult.Unmarshal(m, b)
}
func (m *LoginResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResult.Marshal(b, m, deterministic)
}
func (m *LoginResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResult.Merge(m, src)
}
func (m *LoginResult) XXX_Size() int {
	return xxx_messageInfo_LoginResult.Size(m)
}
func (m *LoginResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResult.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResult proto.InternalMessageInfo

func (m *LoginResult) GetPlatType() LoginType {
	if m != nil {
		return m.PlatType
	}
	return LoginType_Gust
}

func (m *LoginResult) GetPlatId() string {
	if m != nil {
		return m.PlatId
	}
	return ""
}

func (m *LoginResult) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginResult) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

//选服请求
type ChoseServerReq struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChoseServerReq) Reset()         { *m = ChoseServerReq{} }
func (m *ChoseServerReq) String() string { return proto.CompactTextString(m) }
func (*ChoseServerReq) ProtoMessage()    {}
func (*ChoseServerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b916dfaff5dc64ee, []int{2}
}

func (m *ChoseServerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChoseServerReq.Unmarshal(m, b)
}
func (m *ChoseServerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChoseServerReq.Marshal(b, m, deterministic)
}
func (m *ChoseServerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChoseServerReq.Merge(m, src)
}
func (m *ChoseServerReq) XXX_Size() int {
	return xxx_messageInfo_ChoseServerReq.Size(m)
}
func (m *ChoseServerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChoseServerReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChoseServerReq proto.InternalMessageInfo

func (m *ChoseServerReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

//选服返回结果
type ChoseServerRet struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Ret                  int32    `protobuf:"varint,2,opt,name=Ret,proto3" json:"Ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChoseServerRet) Reset()         { *m = ChoseServerRet{} }
func (m *ChoseServerRet) String() string { return proto.CompactTextString(m) }
func (*ChoseServerRet) ProtoMessage()    {}
func (*ChoseServerRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_b916dfaff5dc64ee, []int{3}
}

func (m *ChoseServerRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChoseServerRet.Unmarshal(m, b)
}
func (m *ChoseServerRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChoseServerRet.Marshal(b, m, deterministic)
}
func (m *ChoseServerRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChoseServerRet.Merge(m, src)
}
func (m *ChoseServerRet) XXX_Size() int {
	return xxx_messageInfo_ChoseServerRet.Size(m)
}
func (m *ChoseServerRet) XXX_DiscardUnknown() {
	xxx_messageInfo_ChoseServerRet.DiscardUnknown(m)
}

var xxx_messageInfo_ChoseServerRet proto.InternalMessageInfo

func (m *ChoseServerRet) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ChoseServerRet) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

//登陆网关Token验证请求
type LoginGateCheckReq struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginGateCheckReq) Reset()         { *m = LoginGateCheckReq{} }
func (m *LoginGateCheckReq) String() string { return proto.CompactTextString(m) }
func (*LoginGateCheckReq) ProtoMessage()    {}
func (*LoginGateCheckReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b916dfaff5dc64ee, []int{4}
}

func (m *LoginGateCheckReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginGateCheckReq.Unmarshal(m, b)
}
func (m *LoginGateCheckReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginGateCheckReq.Marshal(b, m, deterministic)
}
func (m *LoginGateCheckReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginGateCheckReq.Merge(m, src)
}
func (m *LoginGateCheckReq) XXX_Size() int {
	return xxx_messageInfo_LoginGateCheckReq.Size(m)
}
func (m *LoginGateCheckReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginGateCheckReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginGateCheckReq proto.InternalMessageInfo

func (m *LoginGateCheckReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginGateCheckReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

//登陆网关Token验证结果返回
type LoginGateCheckRet struct {
	Ret                  int32    `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	NodeId               int32    `protobuf:"varint,2,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginGateCheckRet) Reset()         { *m = LoginGateCheckRet{} }
func (m *LoginGateCheckRet) String() string { return proto.CompactTextString(m) }
func (*LoginGateCheckRet) ProtoMessage()    {}
func (*LoginGateCheckRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_b916dfaff5dc64ee, []int{5}
}

func (m *LoginGateCheckRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginGateCheckRet.Unmarshal(m, b)
}
func (m *LoginGateCheckRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginGateCheckRet.Marshal(b, m, deterministic)
}
func (m *LoginGateCheckRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginGateCheckRet.Merge(m, src)
}
func (m *LoginGateCheckRet) XXX_Size() int {
	return xxx_messageInfo_LoginGateCheckRet.Size(m)
}
func (m *LoginGateCheckRet) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginGateCheckRet.DiscardUnknown(m)
}

var xxx_messageInfo_LoginGateCheckRet proto.InternalMessageInfo

func (m *LoginGateCheckRet) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *LoginGateCheckRet) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

//请求登陆到PlayerService
type LoginToPlayerServiceReq struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	ClientId             uint64   `protobuf:"varint,2,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	UserId               uint64   `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginToPlayerServiceReq) Reset()         { *m = LoginToPlayerServiceReq{} }
func (m *LoginToPlayerServiceReq) String() string { return proto.CompactTextString(m) }
func (*LoginToPlayerServiceReq) ProtoMessage()    {}
func (*LoginToPlayerServiceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b916dfaff5dc64ee, []int{6}
}

func (m *LoginToPlayerServiceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginToPlayerServiceReq.Unmarshal(m, b)
}
func (m *LoginToPlayerServiceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginToPlayerServiceReq.Marshal(b, m, deterministic)
}
func (m *LoginToPlayerServiceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginToPlayerServiceReq.Merge(m, src)
}
func (m *LoginToPlayerServiceReq) XXX_Size() int {
	return xxx_messageInfo_LoginToPlayerServiceReq.Size(m)
}
func (m *LoginToPlayerServiceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginToPlayerServiceReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginToPlayerServiceReq proto.InternalMessageInfo

func (m *LoginToPlayerServiceReq) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *LoginToPlayerServiceReq) GetClientId() uint64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *LoginToPlayerServiceReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

//PlayerService返回登陆结果
type LoginToPlayerServiceRet struct {
	Ret                  int32    `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	NodeId               int32    `protobuf:"varint,2,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginToPlayerServiceRet) Reset()         { *m = LoginToPlayerServiceRet{} }
func (m *LoginToPlayerServiceRet) String() string { return proto.CompactTextString(m) }
func (*LoginToPlayerServiceRet) ProtoMessage()    {}
func (*LoginToPlayerServiceRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_b916dfaff5dc64ee, []int{7}
}

func (m *LoginToPlayerServiceRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginToPlayerServiceRet.Unmarshal(m, b)
}
func (m *LoginToPlayerServiceRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginToPlayerServiceRet.Marshal(b, m, deterministic)
}
func (m *LoginToPlayerServiceRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginToPlayerServiceRet.Merge(m, src)
}
func (m *LoginToPlayerServiceRet) XXX_Size() int {
	return xxx_messageInfo_LoginToPlayerServiceRet.Size(m)
}
func (m *LoginToPlayerServiceRet) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginToPlayerServiceRet.DiscardUnknown(m)
}

var xxx_messageInfo_LoginToPlayerServiceRet proto.InternalMessageInfo

func (m *LoginToPlayerServiceRet) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *LoginToPlayerServiceRet) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

//PlayerSerivce->CenterService同步玩家状态
type UpdatePlayerStatus struct {
	NodeId               int32       `protobuf:"varint,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	UserId               uint64      `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Status               LoginStatus `protobuf:"varint,3,opt,name=Status,proto3,enum=rpc.LoginStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdatePlayerStatus) Reset()         { *m = UpdatePlayerStatus{} }
func (m *UpdatePlayerStatus) String() string { return proto.CompactTextString(m) }
func (*UpdatePlayerStatus) ProtoMessage()    {}
func (*UpdatePlayerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_b916dfaff5dc64ee, []int{8}
}

func (m *UpdatePlayerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlayerStatus.Unmarshal(m, b)
}
func (m *UpdatePlayerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlayerStatus.Marshal(b, m, deterministic)
}
func (m *UpdatePlayerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlayerStatus.Merge(m, src)
}
func (m *UpdatePlayerStatus) XXX_Size() int {
	return xxx_messageInfo_UpdatePlayerStatus.Size(m)
}
func (m *UpdatePlayerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlayerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlayerStatus proto.InternalMessageInfo

func (m *UpdatePlayerStatus) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *UpdatePlayerStatus) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdatePlayerStatus) GetStatus() LoginStatus {
	if m != nil {
		return m.Status
	}
	return LoginStatus_LoginStart
}

func init() {
	proto.RegisterEnum("rpc.LoginStatus", LoginStatus_name, LoginStatus_value)
	proto.RegisterEnum("rpc.LoginType", LoginType_name, LoginType_value)
	proto.RegisterType((*LoginInfo)(nil), "rpc.LoginInfo")
	proto.RegisterType((*LoginResult)(nil), "rpc.LoginResult")
	proto.RegisterType((*ChoseServerReq)(nil), "rpc.ChoseServerReq")
	proto.RegisterType((*ChoseServerRet)(nil), "rpc.ChoseServerRet")
	proto.RegisterType((*LoginGateCheckReq)(nil), "rpc.LoginGateCheckReq")
	proto.RegisterType((*LoginGateCheckRet)(nil), "rpc.LoginGateCheckRet")
	proto.RegisterType((*LoginToPlayerServiceReq)(nil), "rpc.LoginToPlayerServiceReq")
	proto.RegisterType((*LoginToPlayerServiceRet)(nil), "rpc.LoginToPlayerServiceRet")
	proto.RegisterType((*UpdatePlayerStatus)(nil), "rpc.UpdatePlayerStatus")
}

func init() { proto.RegisterFile("proto/rpcproto/login.proto", fileDescriptor_b916dfaff5dc64ee) }

var fileDescriptor_b916dfaff5dc64ee = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x4f, 0x8b, 0x13, 0x31,
	0x14, 0x37, 0xf3, 0xa7, 0xed, 0xbe, 0xea, 0x90, 0x0d, 0xa2, 0xc3, 0x9e, 0xca, 0x9c, 0x4a, 0x0f,
	0x15, 0xd6, 0x8b, 0x20, 0x1e, 0x6a, 0x61, 0x4b, 0x41, 0xdd, 0x12, 0x77, 0x11, 0xbc, 0xc8, 0x6c,
	0xe6, 0xd9, 0x2d, 0x1d, 0x26, 0x63, 0x92, 0x11, 0xf7, 0x03, 0xf8, 0x59, 0xfc, 0x9a, 0x92, 0x4c,
	0x3a, 0x6d, 0x95, 0x15, 0xbc, 0xec, 0xed, 0xfd, 0xde, 0x9b, 0xdf, 0x9f, 0xbc, 0x49, 0xe0, 0xac,
	0x56, 0xd2, 0xc8, 0x17, 0xaa, 0x16, 0x6d, 0x51, 0xca, 0xf5, 0xa6, 0x9a, 0xba, 0x9a, 0x85, 0xaa,
	0x16, 0xd9, 0x2f, 0x02, 0x27, 0xef, 0x6c, 0x73, 0x59, 0x7d, 0x95, 0x6c, 0x02, 0x83, 0x55, 0x99,
	0x9b, 0xab, 0xbb, 0x1a, 0x53, 0x32, 0x22, 0xe3, 0xe4, 0x3c, 0x99, 0xaa, 0x5a, 0x4c, 0xdd, 0x17,
	0xb6, 0xcb, 0xbb, 0x39, 0x7b, 0x06, 0x3d, 0x5b, 0x2f, 0x8b, 0x34, 0x18, 0x91, 0xf1, 0x09, 0xf7,
	0x88, 0x8d, 0x60, 0x38, 0x13, 0x02, 0xb5, 0xbe, 0x92, 0x5b, 0xac, 0xd2, 0xd0, 0x0d, 0x0f, 0x5b,
	0xec, 0x0c, 0x06, 0xab, 0x5c, 0xeb, 0x4f, 0x52, 0x15, 0x69, 0xe4, 0xc6, 0x1d, 0x66, 0x29, 0xf4,
	0x67, 0x42, 0xc8, 0xa6, 0x32, 0x69, 0xec, 0x46, 0x3b, 0x98, 0xfd, 0x24, 0x30, 0x74, 0x39, 0x38,
	0xea, 0xa6, 0x34, 0x0f, 0x94, 0x95, 0x42, 0xc8, 0xd1, 0xb8, 0x98, 0x31, 0xb7, 0x65, 0x36, 0x86,
	0x64, 0x7e, 0x2b, 0x35, 0x7e, 0x44, 0xf5, 0x1d, 0x15, 0xc7, 0x6f, 0x56, 0xfd, 0x5a, 0xa3, 0x5a,
	0x16, 0x2e, 0x47, 0xc4, 0x3d, 0xca, 0x5e, 0xfd, 0xf1, 0xa5, 0x61, 0x4f, 0x21, 0x6e, 0x9d, 0x88,
	0x73, 0x8a, 0x8f, 0x3c, 0x82, 0xbd, 0xc7, 0x0c, 0x4e, 0xdd, 0x31, 0x16, 0xb9, 0xc1, 0xf9, 0x2d,
	0x8a, 0xed, 0x3f, 0x6c, 0xf6, 0xa2, 0xc1, 0x81, 0x68, 0xf6, 0xe6, 0x6f, 0x09, 0xb3, 0x73, 0x22,
	0x9d, 0x93, 0x15, 0xfd, 0x20, 0x0b, 0xf4, 0x9b, 0x89, 0xb9, 0x47, 0x19, 0xc2, 0xf3, 0x76, 0x91,
	0x72, 0x55, 0xe6, 0x77, 0xa8, 0xec, 0x19, 0x36, 0x02, 0x7d, 0x0e, 0x4f, 0x21, 0x87, 0x14, 0xfb,
	0x5b, 0xe7, 0xe5, 0x06, 0xab, 0xdd, 0x9a, 0x23, 0xde, 0xe1, 0x83, 0xec, 0xe1, 0xd1, 0x8a, 0xe6,
	0xf7, 0xd9, 0xfc, 0x4f, 0xd6, 0x0a, 0xd8, 0x75, 0x5d, 0xe4, 0x06, 0xbd, 0x86, 0xc9, 0x4d, 0xa3,
	0xef, 0x8d, 0xb9, 0x8f, 0x12, 0x1c, 0xad, 0x71, 0x0c, 0xbd, 0x96, 0xe9, 0x22, 0x26, 0xe7, 0x74,
	0x7f, 0x9b, 0xda, 0x3e, 0xf7, 0xf3, 0xc9, 0x85, 0xbf, 0x88, 0xde, 0x28, 0x01, 0xd8, 0x41, 0x65,
	0xe8, 0x23, 0xf6, 0x18, 0x06, 0x0e, 0x6f, 0xaa, 0x35, 0x25, 0x6c, 0x08, 0x7d, 0x87, 0xb0, 0xa0,
	0x41, 0x37, 0xba, 0x6c, 0x0c, 0x0d, 0x27, 0x97, 0xfe, 0xe9, 0xb9, 0x2b, 0x3a, 0x80, 0x68, 0xd1,
	0x68, 0xcb, 0x1f, 0x76, 0x4f, 0x80, 0x12, 0xcb, 0xb8, 0xc8, 0x05, 0xde, 0x48, 0xb9, 0xa5, 0x01,
	0x03, 0xe8, 0x2d, 0xa4, 0x5c, 0x97, 0x48, 0x43, 0x76, 0x0a, 0x4f, 0x3a, 0xf6, 0x97, 0xf7, 0xf9,
	0x0f, 0x1a, 0xbd, 0xed, 0x7f, 0x8e, 0xa7, 0xaf, 0x55, 0x2d, 0x6e, 0x7a, 0xee, 0x85, 0xbf, 0xfc,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xd5, 0xb1, 0x39, 0xff, 0x03, 0x00, 0x00,
}
