// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rpcproto/roomgroup.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//queueService-match 从队列匹配上组成一个组
type AddGroupRes struct {
	ClientIdList         []uint64 `protobuf:"varint,1,rep,packed,name=ClientIdList,proto3" json:"ClientIdList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupRes) Reset()         { *m = AddGroupRes{} }
func (m *AddGroupRes) String() string { return proto.CompactTextString(m) }
func (*AddGroupRes) ProtoMessage()    {}
func (*AddGroupRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd50237546b2afc4, []int{0}
}

func (m *AddGroupRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupRes.Unmarshal(m, b)
}
func (m *AddGroupRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupRes.Marshal(b, m, deterministic)
}
func (m *AddGroupRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupRes.Merge(m, src)
}
func (m *AddGroupRes) XXX_Size() int {
	return xxx_messageInfo_AddGroupRes.Size(m)
}
func (m *AddGroupRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupRes.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupRes proto.InternalMessageInfo

func (m *AddGroupRes) GetClientIdList() []uint64 {
	if m != nil {
		return m.ClientIdList
	}
	return nil
}

//queueService-match 从队列匹配上组成一个组
type AddGroupRet struct {
	GroupId              uint64   `protobuf:"varint,1,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupRet) Reset()         { *m = AddGroupRet{} }
func (m *AddGroupRet) String() string { return proto.CompactTextString(m) }
func (*AddGroupRet) ProtoMessage()    {}
func (*AddGroupRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd50237546b2afc4, []int{1}
}

func (m *AddGroupRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupRet.Unmarshal(m, b)
}
func (m *AddGroupRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupRet.Marshal(b, m, deterministic)
}
func (m *AddGroupRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupRet.Merge(m, src)
}
func (m *AddGroupRet) XXX_Size() int {
	return xxx_messageInfo_AddGroupRet.Size(m)
}
func (m *AddGroupRet) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupRet.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupRet proto.InternalMessageInfo

func (m *AddGroupRet) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

// QueueService->RoomService 获取某个房间信息
type GetRoomReq struct {
	RoomUuid             string   `protobuf:"bytes,1,opt,name=RoomUuid,proto3" json:"RoomUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoomReq) Reset()         { *m = GetRoomReq{} }
func (m *GetRoomReq) String() string { return proto.CompactTextString(m) }
func (*GetRoomReq) ProtoMessage()    {}
func (*GetRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd50237546b2afc4, []int{2}
}

func (m *GetRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoomReq.Unmarshal(m, b)
}
func (m *GetRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoomReq.Marshal(b, m, deterministic)
}
func (m *GetRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoomReq.Merge(m, src)
}
func (m *GetRoomReq) XXX_Size() int {
	return xxx_messageInfo_GetRoomReq.Size(m)
}
func (m *GetRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoomReq proto.InternalMessageInfo

func (m *GetRoomReq) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

type GetRoomRes struct {
	Room                 *Room    `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoomRes) Reset()         { *m = GetRoomRes{} }
func (m *GetRoomRes) String() string { return proto.CompactTextString(m) }
func (*GetRoomRes) ProtoMessage()    {}
func (*GetRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd50237546b2afc4, []int{3}
}

func (m *GetRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoomRes.Unmarshal(m, b)
}
func (m *GetRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoomRes.Marshal(b, m, deterministic)
}
func (m *GetRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoomRes.Merge(m, src)
}
func (m *GetRoomRes) XXX_Size() int {
	return xxx_messageInfo_GetRoomRes.Size(m)
}
func (m *GetRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoomRes proto.InternalMessageInfo

func (m *GetRoomRes) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func init() {
	proto.RegisterType((*AddGroupRes)(nil), "rpc.AddGroupRes")
	proto.RegisterType((*AddGroupRet)(nil), "rpc.AddGroupRet")
	proto.RegisterType((*GetRoomReq)(nil), "rpc.GetRoomReq")
	proto.RegisterType((*GetRoomRes)(nil), "rpc.GetRoomRes")
}

func init() { proto.RegisterFile("proto/rpcproto/roomgroup.proto", fileDescriptor_bd50237546b2afc4) }

var fileDescriptor_bd50237546b2afc4 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2a, 0x48, 0x86, 0x32, 0xf2, 0xf3, 0x73, 0xd3, 0x8b, 0xf2, 0x4b, 0x0b, 0xf4,
	0xc0, 0x7c, 0x21, 0xe6, 0xa2, 0x82, 0x64, 0x29, 0x49, 0x34, 0x45, 0x49, 0x89, 0xc5, 0xa9, 0x10,
	0x79, 0x25, 0x43, 0x2e, 0x6e, 0xc7, 0x94, 0x14, 0x77, 0x90, 0x8e, 0xa0, 0xd4, 0x62, 0x21, 0x25,
	0x2e, 0x1e, 0xe7, 0x9c, 0xcc, 0xd4, 0xbc, 0x12, 0xcf, 0x14, 0x9f, 0xcc, 0xe2, 0x12, 0x09, 0x46,
	0x05, 0x66, 0x0d, 0x96, 0x20, 0x14, 0x31, 0x25, 0x75, 0x64, 0x2d, 0x25, 0x42, 0x12, 0x5c, 0xec,
	0x60, 0xb6, 0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x8c, 0xab, 0xa4, 0xc1, 0xc5,
	0xe5, 0x9e, 0x5a, 0x12, 0x94, 0x9f, 0x9f, 0x1b, 0x94, 0x5a, 0x28, 0x24, 0xc5, 0xc5, 0x01, 0x62,
	0x86, 0x96, 0x66, 0x42, 0x14, 0x72, 0x06, 0xc1, 0xf9, 0x4a, 0xea, 0x48, 0x2a, 0x8b, 0x85, 0x24,
	0xb9, 0x58, 0x40, 0xde, 0x00, 0xab, 0xe2, 0x36, 0x62, 0xd5, 0x03, 0x8b, 0x83, 0x85, 0x9c, 0xd8,
	0xa3, 0x58, 0xf5, 0xac, 0x8b, 0x0a, 0x92, 0x93, 0xd8, 0xc0, 0xce, 0x37, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x9e, 0xf4, 0x47, 0xdb, 0x00, 0x01, 0x00, 0x00,
}
