// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db/dbcontrol.proto

package db

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//如果包含Insert+Update，如果存在由更新
type OptType int32

const (
	OptType_None             OptType = 0
	OptType_Find             OptType = 1
	OptType_Insert           OptType = 2
	OptType_Update           OptType = 4
	OptType_Del              OptType = 8
	OptType_Upset            OptType = 16
	OptType_SetOnInsert      OptType = 32
	OptType_InsertNoFallBack OptType = 64
)

var OptType_name = map[int32]string{
	0:  "None",
	1:  "Find",
	2:  "Insert",
	4:  "Update",
	8:  "Del",
	16: "Upset",
	32: "SetOnInsert",
	64: "InsertNoFallBack",
}

var OptType_value = map[string]int32{
	"None":             0,
	"Find":             1,
	"Insert":           2,
	"Update":           4,
	"Del":              8,
	"Upset":            16,
	"SetOnInsert":      32,
	"InsertNoFallBack": 64,
}

func (x OptType) String() string {
	return proto.EnumName(OptType_name, int32(x))
}

func (OptType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_76617f85795d505c, []int{0}
}

type DBControllerReq struct {
	Type                 OptType  `protobuf:"varint,1,opt,name=type,proto3,enum=db.OptType" json:"type,omitempty"`
	Key                  uint64   `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	CollectName          string   `protobuf:"bytes,3,opt,name=collectName,proto3" json:"collectName,omitempty"`
	Condition            []byte   `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	SelectField          []byte   `protobuf:"bytes,5,opt,name=selectField,proto3" json:"selectField,omitempty"`
	MaxRow               int32    `protobuf:"varint,6,opt,name=maxRow,proto3" json:"maxRow,omitempty"`
	Sort                 string   `protobuf:"bytes,7,opt,name=sort,proto3" json:"sort,omitempty"`
	Data                 [][]byte `protobuf:"bytes,8,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBControllerReq) Reset()         { *m = DBControllerReq{} }
func (m *DBControllerReq) String() string { return proto.CompactTextString(m) }
func (*DBControllerReq) ProtoMessage()    {}
func (*DBControllerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_76617f85795d505c, []int{0}
}

func (m *DBControllerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBControllerReq.Unmarshal(m, b)
}
func (m *DBControllerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBControllerReq.Marshal(b, m, deterministic)
}
func (m *DBControllerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBControllerReq.Merge(m, src)
}
func (m *DBControllerReq) XXX_Size() int {
	return xxx_messageInfo_DBControllerReq.Size(m)
}
func (m *DBControllerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DBControllerReq.DiscardUnknown(m)
}

var xxx_messageInfo_DBControllerReq proto.InternalMessageInfo

func (m *DBControllerReq) GetType() OptType {
	if m != nil {
		return m.Type
	}
	return OptType_None
}

func (m *DBControllerReq) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *DBControllerReq) GetCollectName() string {
	if m != nil {
		return m.CollectName
	}
	return ""
}

func (m *DBControllerReq) GetCondition() []byte {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *DBControllerReq) GetSelectField() []byte {
	if m != nil {
		return m.SelectField
	}
	return nil
}

func (m *DBControllerReq) GetMaxRow() int32 {
	if m != nil {
		return m.MaxRow
	}
	return 0
}

func (m *DBControllerReq) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *DBControllerReq) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DBControllerRet struct {
	Type                 OptType  `protobuf:"varint,1,opt,name=type,proto3,enum=db.OptType" json:"type,omitempty"`
	Res                  [][]byte `protobuf:"bytes,2,rep,name=res,proto3" json:"res,omitempty"`
	RowNum               int32    `protobuf:"varint,3,opt,name=rowNum,proto3" json:"rowNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBControllerRet) Reset()         { *m = DBControllerRet{} }
func (m *DBControllerRet) String() string { return proto.CompactTextString(m) }
func (*DBControllerRet) ProtoMessage()    {}
func (*DBControllerRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_76617f85795d505c, []int{1}
}

func (m *DBControllerRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBControllerRet.Unmarshal(m, b)
}
func (m *DBControllerRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBControllerRet.Marshal(b, m, deterministic)
}
func (m *DBControllerRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBControllerRet.Merge(m, src)
}
func (m *DBControllerRet) XXX_Size() int {
	return xxx_messageInfo_DBControllerRet.Size(m)
}
func (m *DBControllerRet) XXX_DiscardUnknown() {
	xxx_messageInfo_DBControllerRet.DiscardUnknown(m)
}

var xxx_messageInfo_DBControllerRet proto.InternalMessageInfo

func (m *DBControllerRet) GetType() OptType {
	if m != nil {
		return m.Type
	}
	return OptType_None
}

func (m *DBControllerRet) GetRes() [][]byte {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *DBControllerRet) GetRowNum() int32 {
	if m != nil {
		return m.RowNum
	}
	return 0
}

type MysqlControllerReq struct {
	Type                 OptType  `protobuf:"varint,1,opt,name=type,proto3,enum=db.OptType" json:"type,omitempty"`
	Key                  uint64   `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	TableName            string   `protobuf:"bytes,3,opt,name=tableName,proto3" json:"tableName,omitempty"`
	ResultJson           string   `protobuf:"bytes,4,opt,name=resultJson,proto3" json:"resultJson,omitempty"`
	Sql                  string   `protobuf:"bytes,5,opt,name=sql,proto3" json:"sql,omitempty"`
	Args                 []string `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MysqlControllerReq) Reset()         { *m = MysqlControllerReq{} }
func (m *MysqlControllerReq) String() string { return proto.CompactTextString(m) }
func (*MysqlControllerReq) ProtoMessage()    {}
func (*MysqlControllerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_76617f85795d505c, []int{2}
}

func (m *MysqlControllerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MysqlControllerReq.Unmarshal(m, b)
}
func (m *MysqlControllerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MysqlControllerReq.Marshal(b, m, deterministic)
}
func (m *MysqlControllerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MysqlControllerReq.Merge(m, src)
}
func (m *MysqlControllerReq) XXX_Size() int {
	return xxx_messageInfo_MysqlControllerReq.Size(m)
}
func (m *MysqlControllerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MysqlControllerReq.DiscardUnknown(m)
}

var xxx_messageInfo_MysqlControllerReq proto.InternalMessageInfo

func (m *MysqlControllerReq) GetType() OptType {
	if m != nil {
		return m.Type
	}
	return OptType_None
}

func (m *MysqlControllerReq) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *MysqlControllerReq) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *MysqlControllerReq) GetResultJson() string {
	if m != nil {
		return m.ResultJson
	}
	return ""
}

func (m *MysqlControllerReq) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

func (m *MysqlControllerReq) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type MysqlControllerRet struct {
	Type                 OptType  `protobuf:"varint,1,opt,name=type,proto3,enum=db.OptType" json:"type,omitempty"`
	Res                  [][]byte `protobuf:"bytes,2,rep,name=res,proto3" json:"res,omitempty"`
	RowNum               int32    `protobuf:"varint,3,opt,name=rowNum,proto3" json:"rowNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MysqlControllerRet) Reset()         { *m = MysqlControllerRet{} }
func (m *MysqlControllerRet) String() string { return proto.CompactTextString(m) }
func (*MysqlControllerRet) ProtoMessage()    {}
func (*MysqlControllerRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_76617f85795d505c, []int{3}
}

func (m *MysqlControllerRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MysqlControllerRet.Unmarshal(m, b)
}
func (m *MysqlControllerRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MysqlControllerRet.Marshal(b, m, deterministic)
}
func (m *MysqlControllerRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MysqlControllerRet.Merge(m, src)
}
func (m *MysqlControllerRet) XXX_Size() int {
	return xxx_messageInfo_MysqlControllerRet.Size(m)
}
func (m *MysqlControllerRet) XXX_DiscardUnknown() {
	xxx_messageInfo_MysqlControllerRet.DiscardUnknown(m)
}

var xxx_messageInfo_MysqlControllerRet proto.InternalMessageInfo

func (m *MysqlControllerRet) GetType() OptType {
	if m != nil {
		return m.Type
	}
	return OptType_None
}

func (m *MysqlControllerRet) GetRes() [][]byte {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *MysqlControllerRet) GetRowNum() int32 {
	if m != nil {
		return m.RowNum
	}
	return 0
}

type RedisControllerReq struct {
	Type                 OptType  `protobuf:"varint,1,opt,name=type,proto3,enum=db.OptType" json:"type,omitempty"`
	Key                  uint64   `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	RKey                 string   `protobuf:"bytes,3,opt,name=rKey,proto3" json:"rKey,omitempty"`
	RValue               string   `protobuf:"bytes,4,opt,name=rValue,proto3" json:"rValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisControllerReq) Reset()         { *m = RedisControllerReq{} }
func (m *RedisControllerReq) String() string { return proto.CompactTextString(m) }
func (*RedisControllerReq) ProtoMessage()    {}
func (*RedisControllerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_76617f85795d505c, []int{4}
}

func (m *RedisControllerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisControllerReq.Unmarshal(m, b)
}
func (m *RedisControllerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisControllerReq.Marshal(b, m, deterministic)
}
func (m *RedisControllerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisControllerReq.Merge(m, src)
}
func (m *RedisControllerReq) XXX_Size() int {
	return xxx_messageInfo_RedisControllerReq.Size(m)
}
func (m *RedisControllerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisControllerReq.DiscardUnknown(m)
}

var xxx_messageInfo_RedisControllerReq proto.InternalMessageInfo

func (m *RedisControllerReq) GetType() OptType {
	if m != nil {
		return m.Type
	}
	return OptType_None
}

func (m *RedisControllerReq) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *RedisControllerReq) GetRKey() string {
	if m != nil {
		return m.RKey
	}
	return ""
}

func (m *RedisControllerReq) GetRValue() string {
	if m != nil {
		return m.RValue
	}
	return ""
}

type RedisControllerRet struct {
	Type                 OptType  `protobuf:"varint,1,opt,name=type,proto3,enum=db.OptType" json:"type,omitempty"`
	Res                  []byte   `protobuf:"bytes,2,opt,name=res,proto3" json:"res,omitempty"`
	RowNum               int32    `protobuf:"varint,3,opt,name=rowNum,proto3" json:"rowNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisControllerRet) Reset()         { *m = RedisControllerRet{} }
func (m *RedisControllerRet) String() string { return proto.CompactTextString(m) }
func (*RedisControllerRet) ProtoMessage()    {}
func (*RedisControllerRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_76617f85795d505c, []int{5}
}

func (m *RedisControllerRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisControllerRet.Unmarshal(m, b)
}
func (m *RedisControllerRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisControllerRet.Marshal(b, m, deterministic)
}
func (m *RedisControllerRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisControllerRet.Merge(m, src)
}
func (m *RedisControllerRet) XXX_Size() int {
	return xxx_messageInfo_RedisControllerRet.Size(m)
}
func (m *RedisControllerRet) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisControllerRet.DiscardUnknown(m)
}

var xxx_messageInfo_RedisControllerRet proto.InternalMessageInfo

func (m *RedisControllerRet) GetType() OptType {
	if m != nil {
		return m.Type
	}
	return OptType_None
}

func (m *RedisControllerRet) GetRes() []byte {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *RedisControllerRet) GetRowNum() int32 {
	if m != nil {
		return m.RowNum
	}
	return 0
}

func init() {
	proto.RegisterEnum("db.OptType", OptType_name, OptType_value)
	proto.RegisterType((*DBControllerReq)(nil), "db.DBControllerReq")
	proto.RegisterType((*DBControllerRet)(nil), "db.DBControllerRet")
	proto.RegisterType((*MysqlControllerReq)(nil), "db.MysqlControllerReq")
	proto.RegisterType((*MysqlControllerRet)(nil), "db.MysqlControllerRet")
	proto.RegisterType((*RedisControllerReq)(nil), "db.RedisControllerReq")
	proto.RegisterType((*RedisControllerRet)(nil), "db.RedisControllerRet")
}

func init() { proto.RegisterFile("db/dbcontrol.proto", fileDescriptor_76617f85795d505c) }

var fileDescriptor_76617f85795d505c = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x51, 0x8b, 0x13, 0x3f,
	0x14, 0xc5, 0xff, 0x69, 0xa7, 0xd3, 0xce, 0xed, 0xf2, 0xdf, 0x70, 0x11, 0xc9, 0xc3, 0xa2, 0x43,
	0x9f, 0x06, 0x1f, 0x2a, 0xe8, 0xa3, 0x2f, 0x52, 0x97, 0x82, 0x8a, 0x5d, 0x88, 0xae, 0x0f, 0x22,
	0x48, 0xa6, 0xb9, 0xc8, 0xb0, 0xe9, 0x64, 0x9a, 0xa4, 0xac, 0xf3, 0x99, 0xfc, 0x5e, 0x7e, 0x0e,
	0x49, 0x76, 0x60, 0x8b, 0x0a, 0x2a, 0xeb, 0xdb, 0xef, 0x9e, 0xcc, 0xc9, 0xcd, 0x39, 0x30, 0x80,
	0xba, 0x7e, 0xac, 0xeb, 0xad, 0x6d, 0x83, 0xb3, 0x66, 0xd9, 0x39, 0x1b, 0x2c, 0x8e, 0x74, 0xbd,
	0xf8, 0xc6, 0xe0, 0xf4, 0x7c, 0xf5, 0xe2, 0x46, 0x37, 0xe4, 0x24, 0xed, 0xf1, 0x21, 0x64, 0xa1,
	0xef, 0x48, 0xb0, 0x92, 0x55, 0xff, 0x3f, 0x99, 0x2f, 0x75, 0xbd, 0xbc, 0xe8, 0xc2, 0xbb, 0xbe,
	0x23, 0x99, 0x0e, 0x90, 0xc3, 0xf8, 0x8a, 0x7a, 0x31, 0x2a, 0x59, 0x95, 0xc9, 0x88, 0x58, 0xc2,
	0x7c, 0x1b, 0xfd, 0xdb, 0xb0, 0x51, 0x3b, 0x12, 0xe3, 0x92, 0x55, 0x85, 0x3c, 0x96, 0xf0, 0x0c,
	0x8a, 0xad, 0x6d, 0x75, 0x13, 0x1a, 0xdb, 0x8a, 0xac, 0x64, 0xd5, 0x89, 0xbc, 0x15, 0xa2, 0xdf,
	0x53, 0xfc, 0x76, 0xdd, 0x90, 0xd1, 0x62, 0x92, 0xce, 0x8f, 0x25, 0xbc, 0x0f, 0xf9, 0x4e, 0x7d,
	0x91, 0xf6, 0x5a, 0xe4, 0x25, 0xab, 0x26, 0x72, 0x98, 0x10, 0x21, 0xf3, 0xd6, 0x05, 0x31, 0x4d,
	0x2b, 0x13, 0x47, 0x4d, 0xab, 0xa0, 0xc4, 0xac, 0x1c, 0x57, 0x27, 0x32, 0xf1, 0xe2, 0xe3, 0x8f,
	0x39, 0xc3, 0x1f, 0xe5, 0x74, 0xe4, 0xc5, 0x28, 0x5d, 0x13, 0x31, 0xbe, 0xc2, 0xd9, 0xeb, 0xcd,
	0x61, 0x97, 0x22, 0x4e, 0xe4, 0x30, 0x2d, 0xbe, 0x32, 0xc0, 0x37, 0xbd, 0xdf, 0x9b, 0x3b, 0x37,
	0x79, 0x06, 0x45, 0x50, 0xb5, 0xa1, 0xa3, 0x1e, 0x6f, 0x05, 0x7c, 0x00, 0xe0, 0xc8, 0x1f, 0x4c,
	0x78, 0xe5, 0x87, 0x1a, 0x0b, 0x79, 0xa4, 0xc4, 0xfb, 0xfc, 0xde, 0xa4, 0xfe, 0x0a, 0x19, 0x31,
	0x76, 0xa1, 0xdc, 0x67, 0x2f, 0xf2, 0x72, 0x1c, 0xfb, 0x89, 0xbc, 0xf8, 0xf4, 0x8b, 0xc7, 0xfe,
	0xd3, 0x3a, 0x3c, 0xa0, 0x24, 0xdd, 0xf8, 0x3b, 0xb7, 0x81, 0x90, 0xb9, 0xd7, 0xd4, 0x0f, 0x45,
	0x24, 0x4e, 0x4b, 0xdf, 0x2b, 0x73, 0xa0, 0x21, 0xff, 0x30, 0xc5, 0x54, 0x3f, 0x2d, 0xfd, 0x9b,
	0x54, 0xec, 0x37, 0xa9, 0x1e, 0x75, 0x30, 0x1d, 0xac, 0x38, 0x83, 0x6c, 0x63, 0x5b, 0xe2, 0xff,
	0x45, 0x5a, 0x37, 0xad, 0xe6, 0x0c, 0x01, 0xf2, 0x97, 0xad, 0x27, 0x17, 0xf8, 0x28, 0xf2, 0x65,
	0xa7, 0x55, 0x20, 0x9e, 0xe1, 0x14, 0xc6, 0xe7, 0x64, 0xf8, 0x0c, 0x0b, 0x98, 0x5c, 0x76, 0x9e,
	0x02, 0xe7, 0x78, 0x0a, 0xf3, 0xb7, 0x14, 0x2e, 0xda, 0xc1, 0x50, 0xe2, 0x3d, 0xe0, 0x37, 0xbc,
	0xb1, 0x6b, 0x65, 0xcc, 0x4a, 0x6d, 0xaf, 0xf8, 0xf3, 0x55, 0xfe, 0x21, 0x5b, 0x3e, 0xd3, 0x75,
	0x9d, 0xa7, 0x1f, 0xf6, 0xe9, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0xd6, 0x1c, 0x0f, 0xc6,
	0x03, 0x00, 0x00,
}
